{"repository":"https://github.com/lukeparser/lukeparser","dockerfilePath":"Dockerfile","startTime":1673200719170,"endTime":1673200732958,"clone":{"startTime":1673200719170,"stdout":"","stderr":"Cloning into '/tmp/dinghy-analysis/lukeparser/lukeparser'...\n","error":null,"endTime":1673200720133,"commit":"c72706639229b47aba2e4548de655590c1030c44"},"originalBuild":{"startTime":1673200720216,"endTime":1673200732876,"error":{"code":1,"killed":false,"signal":null,"cmd":"docker build --no-cache --force-rm -t lukeparser:latest -f /tmp/dinghy-analysis/lukeparser/lukeparser/Dockerfile ."},"stdout":"Sending build context to Docker daemon  1.278MB\r\r\nStep 1/6 : FROM python:slim\nslim: Pulling from library/python\nDigest: sha256:39cecc9cde774f9209ad26a0ab2dc4f5d10ba92d2913a835cebea3b402af8e8b\nStatus: Downloaded newer image for python:slim\n ---> 4a1028aabdec\nStep 2/6 : RUN pip install lukeparser\n ---> Running in 55b862ecc482\nCollecting lukeparser\n  Downloading lukeparser-0.3.28.tar.gz (163 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 163.4/163.4 kB 1.5 MB/s eta 0:00:00\n  Preparing metadata (setup.py): started\n  Preparing metadata (setup.py): finished with status 'error'\n\u001b[91m  error: subprocess-exited-with-error\n  \n  × python setup.py egg_info did not run successfully.\n  │ exit code: 1\n  ╰─> [8 lines of output]\n      Traceback (most recent call last):\n        File \"<string>\", line 2, in <module>\n        File \"<pip-setuptools-caller>\", line 34, in <module>\n        File \"/tmp/pip-install-ox_hguvj/lukeparser_e74cb3f39c384fe68a4b80e4921d350b/setup.py\", line 85, in <module>\n          from luke.parser.markdown import MarkdownParser\n        File \"/tmp/pip-install-ox_hguvj/lukeparser_e74cb3f39c384fe68a4b80e4921d350b/src/luke/parser/markdown.py\", line 5, in <module>\n          from bison import BisonParser, BisonSyntaxError\n      ModuleNotFoundError: No module named 'bison'\n      [end of output]\n  \n  note: This error originates from a subprocess, and is likely not a problem with pip.\n\u001b[0m\u001b[91merror: metadata-generation-failed\n\n× Encountered error while generating package metadata.\n╰─> See above for output.\n\nnote: This is an issue with the package mentioned above, not pip.\nhint: See above for details.\n\u001b[0mRemoving intermediate container 55b862ecc482\n","stderr":"The command '/bin/sh -c pip install lukeparser' returned a non-zero code: 1\n"}}