{"repository":"https://github.com/williano/bona-blog","dockerfilePath":"Dockerfile","startTime":1673013415729,"endTime":1673013534392,"clone":{"startTime":1673013415730,"stdout":"","stderr":"Cloning into '/tmp/dinghy-analysis/williano/bona-blog'...\n","error":null,"endTime":1673013419705,"commit":"31abc168c483f0b867d16b2d516433a42e442957"},"originalBuild":{"startTime":1673013419788,"endTime":1673013534257,"error":{"code":1,"killed":false,"signal":null,"cmd":"docker build --no-cache --force-rm -t bona-blog:latest -f /tmp/dinghy-analysis/williano/bona-blog/Dockerfile ."},"stdout":"Sending build context to Docker daemon  106.8MB\r\r\nStep 1/7 : FROM python:3.7-alpine\n3.7-alpine: Pulling from library/python\nc158987b0551: Already exists\n7ec3a91b66d9: Already exists\n806cc3ffa521: Pulling fs layer\n9a88ff2414d3: Pulling fs layer\n1200e05bcad2: Pulling fs layer\n1200e05bcad2: Waiting\n9a88ff2414d3: Waiting\n806cc3ffa521: Verifying Checksum\n806cc3ffa521: Download complete\n9a88ff2414d3: Verifying Checksum\n9a88ff2414d3: Download complete\n1200e05bcad2: Verifying Checksum\n1200e05bcad2: Download complete\n806cc3ffa521: Pull complete\n9a88ff2414d3: Pull complete\n1200e05bcad2: Pull complete\nDigest: sha256:f1878142fbb04f418c3f67f78708559887ed5487dbe9bfcb191e726548c3f89e\nStatus: Downloaded newer image for python:3.7-alpine\n ---> 23de60bcccb1\nStep 2/7 : ENV PYTHONDONTWRITEBYTECODE 1\n ---> Running in 00bddad7eaac\nRemoving intermediate container 00bddad7eaac\n ---> 7682173de655\nStep 3/7 : ENV PYTHONUNBUFFERED 1\n ---> Running in fadd224af944\nRemoving intermediate container fadd224af944\n ---> 3699397fb589\nStep 4/7 : WORKDIR /code\n ---> Running in d997a3009b7d\nRemoving intermediate container d997a3009b7d\n ---> 4ac97bfa1566\nStep 5/7 : COPY Pipfile Pipfile.lock /code/\n ---> f97fdeb47dc4\nStep 6/7 : RUN pip install pipenv && pipenv install --system\n ---> Running in a06330836830\nCollecting pipenv\n  Downloading pipenv-2022.12.19-py3-none-any.whl (2.9 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 8.8 MB/s eta 0:00:00\nCollecting virtualenv\n  Downloading virtualenv-20.17.1-py3-none-any.whl (8.8 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 40.1 MB/s eta 0:00:00\nRequirement already satisfied: setuptools>=36.2.1 in /usr/local/lib/python3.7/site-packages (from pipenv) (57.5.0)\nCollecting certifi\n  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 KB 5.7 MB/s eta 0:00:00\nCollecting virtualenv-clone>=0.2.5\n  Downloading virtualenv_clone-0.5.7-py3-none-any.whl (6.6 kB)\nCollecting filelock<4,>=3.4.1\n  Downloading filelock-3.9.0-py3-none-any.whl (9.7 kB)\nCollecting importlib-metadata>=4.8.3\n  Downloading importlib_metadata-6.0.0-py3-none-any.whl (21 kB)\nCollecting distlib<1,>=0.3.6\n  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.5/468.5 KB 18.6 MB/s eta 0:00:00\nCollecting platformdirs<3,>=2.4\n  Downloading platformdirs-2.6.2-py3-none-any.whl (14 kB)\nCollecting zipp>=0.5\n  Downloading zipp-3.11.0-py3-none-any.whl (6.6 kB)\nCollecting typing-extensions>=3.6.4\n  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)\nInstalling collected packages: distlib, zipp, virtualenv-clone, typing-extensions, filelock, certifi, platformdirs, importlib-metadata, virtualenv, pipenv\nSuccessfully installed certifi-2022.12.7 distlib-0.3.6 filelock-3.9.0 importlib-metadata-6.0.0 pipenv-2022.12.19 platformdirs-2.6.2 typing-extensions-4.4.0 virtualenv-20.17.1 virtualenv-clone-0.5.7 zipp-3.11.0\n\u001b[91mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\n\u001b[0m\u001b[91mWARNING: You are using pip version 22.0.4; however, version 22.3.1 is available.\nYou should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.\n\u001b[0mInstalling dependencies from Pipfile.lock (7e4a41)...\n\u001b[91mAn error occurred while installing asgiref==3.5.0 ; python_version >= '3.7' --hash=sha256:2f8abc20f7248433085eda803936d98992f1343ddb022065779f37c5da0181d0 --hash=sha256:88d59c13d634dcffe0510be048210188edd79aeccb6a6c9028cdad6f31d730a9! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing coverage==5.1 --hash=sha256:2742c7515b9eb368718cd091bad1a1b44135cc72468c731302b3d641895b83d1 --hash=sha256:0e61d9803d5851849c24f78227939c701ced6704f337cad0a91e0972c51c1ee7 --hash=sha256:e1ea316102ea1e1770724db01998d1603ed921c54a86a2efcb03428d5417e489 --hash=sha256:00f1d23f4336efc3b311ed0d807feb45098fc86dee1ca13b3d6768cdab187c8a --hash=sha256:acf3763ed01af8410fc36afea23707d4ea58ba7e86a8ee915dfb9ceff9ef69d0 --hash=sha256:bb28a7245de68bf29f6fb199545d072d1036a1917dca17a1e75bbb919e14ee8e --hash=sha256:dbe8c6ae7534b5b024296464f387d57c13caa942f6d8e6e0346f27e509f0f768 --hash=sha256:a82b92b04a23d3c8a581fc049228bafde988abacba397d57ce95fe95e0338ab4 --hash=sha256:5c542d1e62eece33c306d66fe0a5c4f7f7b3c08fecc46ead86d7916684b36d6c --hash=sha256:6402bd2fdedabbdb63a316308142597534ea8e1895f4e7d8bf7476c5e8751fef --hash=sha256:1601e480b9b99697a570cea7ef749e88123c04b92d84cedaa01e117436b4a0a9 --hash=sha256:adeb4c5b608574a3d647011af36f7586811a2c1197c861aedb548dd2453b41cd --hash=sha256:bf9cb9a9fd8891e7efd2d44deb24b86d647394b9705b744ff6f8261e6f29a730 --hash=sha256:dec5202bfe6f672d4511086e125db035a52b00f1648d6407cc8e526912c0353a --hash=sha256:f90bfc4ad18450c80b024036eaf91e4a246ae287701aaa88eaebebf150868052 --hash=sha256:2d27a3f742c98e5c6b461ee6ef7287400a1956c11421eb574d843d9ec1f772f0 --hash=sha256:402e1744733df483b93abbf209283898e9f0d67470707e3c7516d84f48524f55 --hash=sha256:a027ef0492ede1e03a8054e3c37b8def89a1e3c471482e9f046906ba4f2aafd2 --hash=sha256:a3f3654d5734a3ece152636aad89f58afc9213c6520062db3978239db122f03c --hash=sha256:782caea581a6e9ff75eccda79287daefd1d2631cc09d642b6ee2d6da21fc0a4e --hash=sha256:b83835506dfc185a319031cf853fa4bb1b3974b1f913f5bb1a0f3d98bdcded04 --hash=sha256:de807ae933cfb7f0c7d9d981a053772452217df2bf38e7e6267c9cbf9545a796 --hash=sha256:dead2ddede4c7ba6cb3a721870f5141c97dc7d85a079edb4bd8d88c3ad5b20c7 --hash=sha256:c317eaf5ff46a34305b202e73404f55f7389ef834b8dbf4da09b9b9b37f76dd2 --hash=sha256:0cb4be7e784dcdc050fc58ef05b71aa8e89b7e6636b99967fadbdba694cf2b65 --hash=sha256:7a5bdad4edec57b5fb8dae7d3ee58622d626fd3a0be0dfceda162a7035885ecf --hash=sha256:01333e1bd22c59713ba8a79f088b3955946e293114479bbfc2e37d522be03355 --hash=sha256:79a3cfd6346ce6c13145731d39db47b7a7b859c0272f02cdb89a3bdcbae233a0 --hash=sha256:8fa0cbc7ecad630e5b0f4f35b0f6ad419246b02bc750de7ac66db92667996d24 --hash=sha256:5f2294dbf7875b991c381e3d5af2bcc3494d836affa52b809c91697449d0eda6 --hash=sha256:66460ab1599d3cf894bb6baee8c684788819b71a5dc1e8fa2ecc152e5d752019! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django==3.1.14 --hash=sha256:72a4a5a136a214c39cf016ccdd6b69e2aa08c7479c66d93f3a9b5e4bb9d8a347 --hash=sha256:0fabc786489af16ad87a8c170ba9d42bfd23f7b699bd5ef05675864e8d012859! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django-ckeditor==6.0.0 --hash=sha256:cc2d377f1bdcd4ca1540caeebe85f7e2cd006198d57328ef6c718d3eaa5a0846 --hash=sha256:29fd1a333cb9741ac2c3fd4e427a5c00115ed33a2389716a09af7656022dcdde! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django-crispy-forms==1.11.1 --hash=sha256:2ea206f35a9554597b89315ea52737d32d2fd9f5304e79a469a08887aa0824b0 --hash=sha256:5c600dea66e2f435f774fe2c4cacfb5b5eb9914dd6da0728edd174b95f6956fd! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django-filter==2.4.0 --hash=sha256:e00d32cebdb3d54273c48f4f878f898dced8d5dfaad009438fe61ebdf535ace1 --hash=sha256:84e9d5bb93f237e451db814ed422a3a625751cbc9968b484ecc74964a8696b06! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django-js-asset==2.0.0 ; python_version >= '3.6' --hash=sha256:86f9f300d682537ddaf0487dc2ab356581b8f50c069bdba91d334a46e449f923 --hash=sha256:adc1ee1efa853fad42054b540c02205344bb406c9bddf87c9e5377a41b7db90f! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django-taggit==1.3.0 --hash=sha256:609b0223d8a652f3fae088b7fd29f294fdadaca2d7931d45c27d6c59b02fdf31 --hash=sha256:4a833bf71f4c2deddd9745924eee53be1c075d7f0020a06f12e29fa3d752732d! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing djangorestframework==3.11.2 --hash=sha256:5cc724dc4b076463497837269107e1995b1fbc917468d1b92d188fd1af9ea789 --hash=sha256:a5967b68a04e0d97d10f4df228e30f5a2d82ba63b9d03e1759f84993b7bf1b53! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing pillow==9.0.1 --hash=sha256:1d19397351f73a88904ad1aee421e800fe4bbcd1aeee6435fb62d0a05ccd1030 --hash=sha256:855c583f268edde09474b081e3ddcd5cf3b20c12f26e0d434e1386cc5d318e7a --hash=sha256:514ceac913076feefbeaf89771fd6febde78b0c4c1b23aaeab082c41c694e81b --hash=sha256:d3c5c79ab7dfce6d88f1ba639b77e77a17ea33a01b07b99840d6ed08031cb2a7 --hash=sha256:80fe64a6deb6fcfdf7b8386f2cf216d329be6f2781f7d90304351811fb591360 --hash=sha256:335ace1a22325395c4ea88e00ba3dc89ca029bd66bd5a3c382d53e44f0ccd77e --hash=sha256:db6d9fac65bd08cea7f3540b899977c6dee9edad959fa4eaf305940d9cbd861c --hash=sha256:6c8bc8238a7dfdaf7a75f5ec5a663f4173f8c367e5a39f87e720495e1eed75fa --hash=sha256:b9618823bd237c0d2575283f2939655f54d51b4527ec3972907a927acbcc5bfc --hash=sha256:9bfdb82cdfeccec50aad441afc332faf8606dfa5e8efd18a6692b5d6e79f00fd --hash=sha256:0f29d831e2151e0b7b39981756d201f7108d3d215896212ffe2e992d06bfe049 --hash=sha256:d9d7942b624b04b895cb95af03a23407f17646815495ce4547f0e60e0b06f58e --hash=sha256:a5d24e1d674dd9d72c66ad3ea9131322819ff86250b30dc5821cbafcfa0b96b4 --hash=sha256:1c3c33ac69cf059bbb9d1a71eeaba76781b450bc307e2291f8a4764d779a6b28 --hash=sha256:14d4b1341ac07ae07eb2cc682f459bec932a380c3b122f5540432d8977e64eae --hash=sha256:6295f6763749b89c994fcb6d8a7f7ce03c3992e695f89f00b741b4580b199b7e --hash=sha256:effb7749713d5317478bb3acb3f81d9d7c7f86726d41c1facca068a04cf5bb4c --hash=sha256:2632d0f846b7c7600edf53c48f8f9f1e13e62f66a6dbc15191029d950bfed976 --hash=sha256:413ce0bbf9fc6278b2d63309dfeefe452835e1c78398efb431bab0672fe9274e --hash=sha256:cef9c85ccbe9bee00909758936ea841ef12035296c748aaceee535969e27d31b --hash=sha256:253e8a302a96df6927310a9d44e6103055e8fb96a6822f8b7f514bb7ef77de56 --hash=sha256:a9f44cd7e162ac6191491d7249cceb02b8116b0f7e847ee33f739d7cb1ea1f70 --hash=sha256:ede5af4a2702444a832a800b8eb7f0a7a1c0eed55b644642e049c98d589e5092 --hash=sha256:f154d173286a5d1863637a7dcd8c3437bb557520b01bddb0be0258dcb72696b5 --hash=sha256:7f7609a718b177bf171ac93cea9fd2ddc0e03e84d8fa4e887bdfc39671d46b00 --hash=sha256:5100b45a4638e3c00e4d2320d3193bdabb2d75e79793af7c3eb139e4f569f16f --hash=sha256:011233e0c42a4a7836498e98c1acf5e744c96a67dd5032a6f666cc1fb97eab97 --hash=sha256:12875d118f21cf35604176872447cdb57b07126750a33748bac15e77f90f1f9c --hash=sha256:b5b3f092fe345c03bca1e0b687dfbb39364b21ebb8ba90e3fa707374b7915204 --hash=sha256:528a2a692c65dd5cafc130de286030af251d2ee0483a5bf50c9348aefe834e8a --hash=sha256:718856856ba31f14f13ba885ff13874be7fefc53984d2832458f12c38205f7f7 --hash=sha256:f25ed6e28ddf50de7e7ea99d7a976d6a9c415f03adcaac9c41ff6ff41b6d86ac --hash=sha256:d21237d0cd37acded35154e29aec853e945950321dd2ffd1a7d86fe686814669 --hash=sha256:80ca33961ced9c63358056bd08403ff866512038883e74f3a4bf88ad3eb66838 --hash=sha256:81c4b81611e3a3cb30e59b0cf05b888c675f97e3adb2c8672c3154047980726b! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing pyenchant==3.2.0 --hash=sha256:f22cc6e342d4e6a027296c59ae8ad4d5b2f281da1ecbe0e839a9e5f5d243b33d --hash=sha256:f649f36fa90cb950d10b1a70bca50be7799ec759aa478353f08dcef579c097ee --hash=sha256:6b97e9a9f132fa7c9029a6635d821ccad67d4980e68186d02c765b4256b6f152 --hash=sha256:5f5fbf99283136ad0e56660343ec4f16713981e340984ce9487de756fce022c6! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing pytz==2020.1 --hash=sha256:a494d53b6d39c3c6e44c3bec237336e14305e4f29bbf800b599253057fbb79ed --hash=sha256:c35965d010ce31b23eeb663ed3cc8c906275d6be1a34393a1d73a41febf4a048! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing six==1.15.0 --hash=sha256:8b74bedcbbbaca38ff6d7491d76f2b06b3592611af620f8426e82dddb04a5ced --hash=sha256:30639c035cdb23534cd4aa2dd52c3bf48f06e5f4a941509c8bafd8ce11080259! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing sqlparse==0.4.2 ; python_version >= '3.5' --hash=sha256:0c00730c74263a94e5a9919ade150dfc3b19c574389985446148402998287dae --hash=sha256:48719e356bb8b42991bdbb1e8b83223757b93789c00910a616a071910ca4a64d! Will try again.\n\u001b[0mInstalling initially failed dependencies...\n\u001b[91m[pipenv.exceptions.InstallError]: Collecting asgiref==3.5.0\n[pipenv.exceptions.InstallError]:   Using cached asgiref-3.5.0-py3-none-any.whl (22 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting coverage==5.1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached coverage-5.1.tar.gz (687 kB)\n[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting django==3.1.14\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached Django-3.1.14-py3-none-any.whl (7.8 MB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting django-crispy-forms==1.11.1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached django_crispy_forms-1.11.1-py3-none-any.whl (108 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting django-filter==2.4.0\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached django_filter-2.4.0-py3-none-any.whl (73 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting django-js-asset==2.0.0\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached django_js_asset-2.0.0-py3-none-any.whl (4.9 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting django-taggit==1.3.0\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached django_taggit-1.3.0-py3-none-any.whl (45 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting djangorestframework==3.11.2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached djangorestframework-3.11.2-py3-none-any.whl (911 kB)\n[pipenv.exceptions.InstallError]: Collecting pillow==9.0.1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached Pillow-9.0.1.tar.gz (49.5 MB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Building wheels for collected packages: coverage, pillow\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Building wheel for coverage (setup.py): started\n[pipenv.exceptions.InstallError]:   Building wheel for coverage (setup.py): finished with status 'done'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Created wheel for coverage: filename=coverage-5.1-py3-none-any.whl size=195667 sha256=fc79d761fd983108def82a6aa07abde83634688f0dbc774d15931667f1f29dbc\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Stored in directory: /root/.cache/pipenv/wheels/ff/91/08/00104e36d9ec686064b0c7d274c727d3af07135099dbb6623f\n[pipenv.exceptions.InstallError]:   Building wheel for pillow (setup.py): started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Building wheel for pillow (setup.py): finished with status 'error'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Running setup.py clean for pillow\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Successfully built coverage\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Failed to build pillow\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Installing collected packages: pillow, djangorestframework, django-taggit, django-js-asset, django-filter, django-crispy-forms, django, coverage, asgiref\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Running setup.py install for pillow: started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Running setup.py install for pillow: finished with status 'error'\n[pipenv.exceptions.InstallError]: error: subprocess-exited-with-error\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   × python setup.py bdist_wheel did not run successfully.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   │ exit code: 1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   ╰─> [177 lines of output]\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running bdist_wheel\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build_py\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-3.7\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/Image.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/features.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/_version.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/__main__.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/_util.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running egg_info\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       writing src/Pillow.egg-info/PKG-INFO\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       writing dependency_links to src/Pillow.egg-info/dependency_links.txt\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       writing top-level names to src/Pillow.egg-info/top_level.txt\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       reading manifest file 'src/Pillow.egg-info/SOURCES.txt'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       reading manifest template 'MANIFEST.in'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no files found matching '*.c'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no files found matching '*.h'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no files found matching '*.sh'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files found matching '.appveyor.yml'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files found matching '.clang-format'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files found matching '.coveragerc'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files found matching '.editorconfig'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files found matching '.readthedocs.yml'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files found matching 'codecov.yml'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files matching '.git*' found anywhere in distribution\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files matching '*.pyc' found anywhere in distribution\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files matching '*.so' found anywhere in distribution\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       no previously-included directories found matching '.ci'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       adding license file 'LICENSE'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       writing manifest file 'src/Pillow.egg-info/SOURCES.txt'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: build_py: byte-compiling is disabled, skipping.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build_ext\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       The headers or library files could not be found for zlib,\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       a required dependency when compiling Pillow from source.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       Please see the install instructions at:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:          https://pillow.readthedocs.io/en/latest/installation.html\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       Traceback (most recent call last):\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/tmp/pip-install-mjrhmxky/pillow_8679f3a65425477dad04db97d65cdc9f/setup.py\", line 996, in <module>\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           zip_safe=not (debug_build() or PLATFORM_MINGW),\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/site-packages/setuptools/__init__.py\", line 153, in setup\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           return distutils.core.setup(**attrs)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/core.py\", line 148, in setup\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           dist.run_commands()\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/dist.py\", line 966, in run_commands\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           self.run_command(cmd)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/dist.py\", line 985, in run_command\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           cmd_obj.run()\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/site-packages/wheel/bdist_wheel.py\", line 325, in run\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           self.run_command(\"build\")\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/cmd.py\", line 313, in run_command\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           self.distribution.run_command(command)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/dist.py\", line 985, in run_command\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           cmd_obj.run()\n[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/command/build.py\", line 135, in run\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           self.run_command(cmd_name)\n[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/cmd.py\", line 313, in run_command\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           self.distribution.run_command(command)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/dist.py\", line 985, in run_command\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           cmd_obj.run()\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/site-packages/setuptools/command/build_ext.py\", line 79, in run\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           _build_ext.run(self)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/command/build_ext.py\", line 340, in run\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           self.build_extensions()\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/tmp/pip-install-mjrhmxky/pillow_8679f3a65425477dad04db97d65cdc9f/setup.py\", line 804, in build_extensions\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           raise RequiredDependencyException(f)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       __main__.RequiredDependencyException: zlib\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       During handling of the above exception, another exception occurred:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       Traceback (most recent call last):\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"<string>\", line 36, in <module>\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"<pip-setuptools-caller>\", line 34, in <module>\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/tmp/pip-install-mjrhmxky/pillow_8679f3a65425477dad04db97d65cdc9f/setup.py\", line 1009, in <module>\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           raise RequiredDependencyException(msg)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       __main__.RequiredDependencyException:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       The headers or library files could not be found for zlib,\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       a required dependency when compiling Pillow from source.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n[pipenv.exceptions.InstallError]:       Please see the install instructions at:\n[pipenv.exceptions.InstallError]:          https://pillow.readthedocs.io/en/latest/installation.html\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       [end of output]\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.\n[pipenv.exceptions.InstallError]:   ERROR: Failed building wheel for pillow\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   error: subprocess-exited-with-error\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   × Running setup.py install for pillow did not run successfully.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   │ exit code: 1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   ╰─> [179 lines of output]\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running install\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build_py\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-3.7\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/Image.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/features.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/_version.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/__main__.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/_util.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.7/PIL\n[pipenv.exceptions.InstallError]:       copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.7/PIL\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running egg_info\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       writing src/Pillow.egg-info/PKG-INFO\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       writing dependency_links to src/Pillow.egg-info/dependency_links.txt\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       writing top-level names to src/Pillow.egg-info/top_level.txt\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       reading manifest file 'src/Pillow.egg-info/SOURCES.txt'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       reading manifest template 'MANIFEST.in'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no files found matching '*.c'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no files found matching '*.h'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no files found matching '*.sh'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files found matching '.appveyor.yml'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files found matching '.clang-format'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files found matching '.coveragerc'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files found matching '.editorconfig'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files found matching '.readthedocs.yml'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files found matching 'codecov.yml'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files matching '.git*' found anywhere in distribution\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files matching '*.pyc' found anywhere in distribution\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: no previously-included files matching '*.so' found anywhere in distribution\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       no previously-included directories found matching '.ci'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       adding license file 'LICENSE'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       writing manifest file 'src/Pillow.egg-info/SOURCES.txt'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: build_py: byte-compiling is disabled, skipping.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build_ext\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n[pipenv.exceptions.InstallError]:       The headers or library files could not be found for zlib,\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       a required dependency when compiling Pillow from source.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n[pipenv.exceptions.InstallError]:       Please see the install instructions at:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:          https://pillow.readthedocs.io/en/latest/installation.html\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       Traceback (most recent call last):\n[pipenv.exceptions.InstallError]:         File \"/tmp/pip-install-mjrhmxky/pillow_8679f3a65425477dad04db97d65cdc9f/setup.py\", line 996, in <module>\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           zip_safe=not (debug_build() or PLATFORM_MINGW),\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/site-packages/setuptools/__init__.py\", line 153, in setup\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           return distutils.core.setup(**attrs)\n[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/core.py\", line 148, in setup\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           dist.run_commands()\n[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/dist.py\", line 966, in run_commands\n[pipenv.exceptions.InstallError]:           self.run_command(cmd)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/dist.py\", line 985, in run_command\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           cmd_obj.run()\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/site-packages/setuptools/command/install.py\", line 61, in run\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           return orig.install.run(self)\n[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/command/install.py\", line 545, in run\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           self.run_command('build')\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/cmd.py\", line 313, in run_command\n[pipenv.exceptions.InstallError]:           self.distribution.run_command(command)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/dist.py\", line 985, in run_command\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           cmd_obj.run()\n[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/command/build.py\", line 135, in run\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           self.run_command(cmd_name)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/cmd.py\", line 313, in run_command\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           self.distribution.run_command(command)\n[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/dist.py\", line 985, in run_command\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           cmd_obj.run()\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/site-packages/setuptools/command/build_ext.py\", line 79, in run\n[pipenv.exceptions.InstallError]:           _build_ext.run(self)\n[pipenv.exceptions.InstallError]:         File \"/usr/local/lib/python3.7/distutils/command/build_ext.py\", line 340, in run\n[pipenv.exceptions.InstallError]:           self.build_extensions()\n[pipenv.exceptions.InstallError]:         File \"/tmp/pip-install-mjrhmxky/pillow_8679f3a65425477dad04db97d65cdc9f/setup.py\", line 804, in build_extensions\n[pipenv.exceptions.InstallError]:           raise RequiredDependencyException(f)\n[pipenv.exceptions.InstallError]:       __main__.RequiredDependencyException: zlib\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       During handling of the above exception, another exception occurred:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       Traceback (most recent call last):\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"<string>\", line 36, in <module>\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         File \"<pip-setuptools-caller>\", line 34, in <module>\n[pipenv.exceptions.InstallError]:         File \"/tmp/pip-install-mjrhmxky/pillow_8679f3a65425477dad04db97d65cdc9f/setup.py\", line 1009, in <module>\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:           raise RequiredDependencyException(msg)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       __main__.RequiredDependencyException:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       The headers or library files could not be found for zlib,\n[pipenv.exceptions.InstallError]:       a required dependency when compiling Pillow from source.\n[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       Please see the install instructions at:\n[pipenv.exceptions.InstallError]:          https://pillow.readthedocs.io/en/latest/installation.html\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       [end of output]\n[pipenv.exceptions.InstallError]:   \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: error: legacy-install-failure\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: \n[pipenv.exceptions.InstallError]: × Encountered error while trying to install package.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: ╰─> pillow\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: note: This is an issue with the package mentioned above, not pip.\n[pipenv.exceptions.InstallError]: hint: See above for output from the failure.\n\u001b[0m\u001b[91mERROR: Couldn't install package: [Requirement(_name='asgiref', vcs=None, req=NamedRequirement(name='asgiref', version='==3.5.0', req=Requirement.parse('asgiref==3.5.0; python_version >= \"3.7\"'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=asgiref, path=None, uri=None, extras=(), markers=python_version >= '3.7', vcs=None, specifier===3.5.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=asgiref==3.5.0)>), markers='python_version >= \"3.7\"', _specifiers='==3.5.0', index=None, editable=False, hashes=frozenset({'sha256:2f8abc20f7248433085eda803936d98992f1343ddb022065779f37c5da0181d0', 'sha256:88d59c13d634dcffe0510be048210188edd79aeccb6a6c9028cdad6f31d730a9'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=asgiref, path=None, uri=None, extras=(), markers=python_version >= '3.7', vcs=None, specifier===3.5.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=asgiref==3.5.0)>, _ireq=None), Requirement(_name='coverage', vcs=None, req=NamedRequirement(name='coverage', version='==5.1', req=Requirement.parse('coverage==5.1'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=coverage, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===5.1, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=coverage==5.1)>), markers=None, _specifiers='==5.1', index='pypi', editable=False, hashes=frozenset({'sha256:2742c7515b9eb368718cd091bad1a1b44135cc72468c731302b3d641895b83d1', 'sha256:0e61d9803d5851849c24f78227939c701ced6704f337cad0a91e0972c51c1ee7', 'sha256:e1ea316102ea1e1770724db01998d1603ed921c54a86a2efcb03428d5417e489', 'sha256:00f1d23f4336efc3b311ed0d807feb45098fc86dee1ca13b3d6768cdab187c8a', 'sha256:acf3763ed01af8410fc36afea23707d4ea58ba7e86a8ee915dfb9ceff9ef69d0', 'sha256:bb28a7245de68bf29f6fb199545d072d1036a1917dca17a1e75bbb919e14ee8e', 'sha256:dbe8c6ae7534b5b024296464f387d57c13caa942f6d8e6e0346f27e509f0f768', 'sha256:a82b92b04a23d3c8a581fc049228bafde988abacba397d57ce95fe95e0338ab4', 'sha256:5c542d1e62eece33c306d66fe0a5c4f7f7b3c08fecc46ead86d7916684b36d6c', 'sha256:6402bd2fdedabbdb63a316308142597534ea8e1895f4e7d8bf7476c5e8751fef', 'sha256:1601e480b9b99697a570cea7ef749e88123c04b92d84cedaa01e117436b4a0a9', 'sha256:adeb4c5b608574a3d647011af36f7586811a2c1197c861aedb548dd2453b41cd', 'sha256:bf9cb9a9fd8891e7efd2d44deb24b86d647394b9705b744ff6f8261e6f29a730', 'sha256:dec5202bfe6f672d4511086e125db035a52b00f1648d6407cc8e526912c0353a', 'sha256:f90bfc4ad18450c80b024036eaf91e4a246ae287701aaa88eaebebf150868052', 'sha256:2d27a3f742c98e5c6b461ee6ef7287400a1956c11421eb574d843d9ec1f772f0', 'sha256:402e1744733df483b93abbf209283898e9f0d67470707e3c7516d84f48524f55', 'sha256:a027ef0492ede1e03a8054e3c37b8def89a1e3c471482e9f046906ba4f2aafd2', 'sha256:a3f3654d5734a3ece152636aad89f58afc9213c6520062db3978239db122f03c', 'sha256:782caea581a6e9ff75eccda79287daefd1d2631cc09d642b6ee2d6da21fc0a4e', 'sha256:b83835506dfc185a319031cf853fa4bb1b3974b1f913f5bb1a0f3d98bdcded04', 'sha256:de807ae933cfb7f0c7d9d981a053772452217df2bf38e7e6267c9cbf9545a796', 'sha256:dead2ddede4c7ba6cb3a721870f5141c97dc7d85a079edb4bd8d88c3ad5b20c7', 'sha256:c317eaf5ff46a34305b202e73404f55f7389ef834b8dbf4da09b9b9b37f76dd2', 'sha256:0cb4be7e784dcdc050fc58ef05b71aa8e89b7e6636b99967fadbdba694cf2b65', 'sha256:7a5bdad4edec57b5fb8dae7d3ee58622d626fd3a0be0dfceda162a7035885ecf', 'sha256:01333e1bd22c59713ba8a79f088b3955946e293114479bbfc2e37d522be03355', 'sha256:79a3cfd6346ce6c13145731d39db47b7a7b859c0272f02cdb89a3bdcbae233a0', 'sha256:8fa0cbc7ecad630e5b0f4f35b0f6ad419246b02bc750de7ac66db92667996d24', 'sha256:5f2294dbf7875b991c381e3d5af2bcc3494d836affa52b809c91697449d0eda6', 'sha256:66460ab1599d3cf894bb6baee8c684788819b71a5dc1e8fa2ecc152e5d752019'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=coverage, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===5.1, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=coverage==5.1)>, _ireq=None), Requirement(_name='django', vcs=None, req=NamedRequirement(name='django', version='==3.1.14', req=Requirement.parse('django==3.1.14'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=django, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===3.1.14, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django==3.1.14)>), markers=None, _specifiers='==3.1.14', index='pypi', editable=False, hashes=frozenset({'sha256:72a4a5a136a214c39cf016ccdd6b69e2aa08c7479c66d93f3a9b5e4bb9d8a347', 'sha256:0fabc786489af16ad87a8c170ba9d42bfd23f7b699bd5ef05675864e8d012859'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=django, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===3.1.14, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django==3.1.14)>, _ireq=None), Requirement(_name='django-crispy-forms', vcs=None, req=NamedRequirement(name='django-crispy-forms', version='==1.11.1', req=Requirement.parse('django-crispy-forms==1.11.1'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=django-crispy-forms, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===1.11.1, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django-crispy-forms==1.11.1)>), markers=None, _specifiers='==1.11.1', index='pypi', editable=False, hashes=frozenset({'sha256:2ea206f35a9554597b89315ea52737d32d2fd9f5304e79a469a08887aa0824b0', 'sha256:5c600dea66e2f435f774fe2c4cacfb5b5eb9914dd6da0728edd174b95f6956fd'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=django-crispy-forms, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===1.11.1, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django-crispy-forms==1.11.1)>, _ireq=None), Requirement(_name='django-filter', vcs=None, req=NamedRequirement(name='django-filter', version='==2.4.0', req=Requirement.parse('django-filter==2.4.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=django-filter, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.4.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django-filter==2.4.0)>), markers=None, _specifiers='==2.4.0', index='pypi', editable=False, hashes=frozenset({'sha256:e00d32cebdb3d54273c48f4f878f898dced8d5dfaad009438fe61ebdf535ace1', 'sha256:84e9d5bb93f237e451db814ed422a3a625751cbc9968b484ecc74964a8696b06'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=django-filter, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.4.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django-filter==2.4.0)>, _ireq=None), Requirement(_name='django-js-asset', vcs=None, req=NamedRequirement(name='django-js-asset', version='==2.0.0', req=Requirement.parse('django-js-asset==2.0.0; python_version >= \"3.6\"'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=django-js-asset, path=None, uri=None, extras=(), markers=python_version >= '3.6', vcs=None, specifier===2.0.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django-js-asset==2.0.0)>), markers='python_version >= \"3.6\"', _specifiers='==2.0.0', index=None, editable=False, hashes=frozenset({'sha256:86f9f300d682537ddaf0487dc2ab356581b8f50c069bdba91d334a46e449f923', 'sha256:adc1ee1efa853fad42054b540c02205344bb406c9bddf87c9e5377a41b7db90f'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=django-js-asset, path=None, uri=None, extras=(), markers=python_version >= '3.6', vcs=None, specifier===2.0.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django-js-asset==2.0.0)>, _ireq=None), Requirement(_name='django-taggit', vcs=None, req=NamedRequirement(name='django-taggit', version='==1.3.0', req=Requirement.parse('django-taggit==1.3.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=django-taggit, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===1.3.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django-taggit==1.3.0)>), markers=None, _specifiers='==1.3.0', index='pypi', editable=False, hashes=frozenset({'sha256:609b0223d8a652f3fae088b7fd29f294fdadaca2d7931d45c27d6c59b02fdf31', 'sha256:4a833bf71f4c2deddd9745924eee53be1c075d7f0020a06f12e29fa3d752732d'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=django-taggit, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===1.3.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django-taggit==1.3.0)>, _ireq=None), Requirement(_name='djangorestframework', vcs=None, req=NamedRequirement(name='djangorestframework', version='==3.11.2', req=Requirement.parse('djangorestframework==3.11.2'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=djangorestframework, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===3.11.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=djangorestframework==3.11.2)>), markers=None, _specifiers='==3.11.2', index='pypi', editable=False, hashes=frozenset({'sha256:5cc724dc4b076463497837269107e1995b1fbc917468d1b92d188fd1af9ea789', 'sha256:a5967b68a04e0d97d10f4df228e30f5a2d82ba63b9d03e1759f84993b7bf1b53'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=djangorestframework, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===3.11.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=djangorestframework==3.11.2)>, _ireq=None), Requirement(_name='pillow', vcs=None, req=NamedRequirement(name='pillow', version='==9.0.1', req=Requirement.parse('pillow==9.0.1'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=pillow, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===9.0.1, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=pillow==9.0.1)>), markers=None, _specifiers='==9.0.1', index='pypi', editable=False, hashes=frozenset({'sha256:1d19397351f73a88904ad1aee421e800fe4bbcd1aeee6435fb62d0a05ccd1030', 'sha256:855c583f268edde09474b081e3ddcd5cf3b20c12f26e0d434e1386cc5d318e7a', 'sha256:514ceac913076feefbeaf89771fd6febde78b0c4c1b23aaeab082c41c694e81b', 'sha256:d3c5c79ab7dfce6d88f1ba639b77e77a17ea33a01b07b99840d6ed08031cb2a7', 'sha256:80fe64a6deb6fcfdf7b8386f2cf216d329be6f2781f7d90304351811fb591360', 'sha256:335ace1a22325395c4ea88e00ba3dc89ca029bd66bd5a3c382d53e44f0ccd77e', 'sha256:db6d9fac65bd08cea7f3540b899977c6dee9edad959fa4eaf305940d9cbd861c', 'sha256:6c8bc8238a7dfdaf7a75f5ec5a663f4173f8c367e5a39f87e720495e1eed75fa', 'sha256:b9618823bd237c0d2575283f2939655f54d51b4527ec3972907a927acbcc5bfc', 'sha256:9bfdb82cdfeccec50aad441afc332faf8606dfa5e8efd18a6692b5d6e79f00fd', 'sha256:0f29d831e2151e0b7b39981756d201f7108d3d215896212ffe2e992d06bfe049', 'sha256:d9d7942b624b04b895cb95af03a23407f17646815495ce4547f0e60e0b06f58e', 'sha256:a5d24e1d674dd9d72c66ad3ea9131322819ff86250b30dc5821cbafcfa0b96b4', 'sha256:1c3c33ac69cf059bbb9d1a71eeaba76781b450bc307e2291f8a4764d779a6b28', 'sha256:14d4b1341ac07ae07eb2cc682f459bec932a380c3b122f5540432d8977e64eae', 'sha256:6295f6763749b89c994fcb6d8a7f7ce03c3992e695f89f00b741b4580b199b7e', 'sha256:effb7749713d5317478bb3acb3f81d9d7c7f86726d41c1facca068a04cf5bb4c', 'sha256:2632d0f846b7c7600edf53c48f8f9f1e13e62f66a6dbc15191029d950bfed976', 'sha256:413ce0bbf9fc6278b2d63309dfeefe452835e1c78398efb431bab0672fe9274e', 'sha256:cef9c85ccbe9bee00909758936ea841ef12035296c748aaceee535969e27d31b', 'sha256:253e8a302a96df6927310a9d44e6103055e8fb96a6822f8b7f514bb7ef77de56', 'sha256:a9f44cd7e162ac6191491d7249cceb02b8116b0f7e847ee33f739d7cb1ea1f70', 'sha256:ede5af4a2702444a832a800b8eb7f0a7a1c0eed55b644642e049c98d589e5092', 'sha256:f154d173286a5d1863637a7dcd8c3437bb557520b01bddb0be0258dcb72696b5', 'sha256:7f7609a718b177bf171ac93cea9fd2ddc0e03e84d8fa4e887bdfc39671d46b00', 'sha256:5100b45a4638e3c00e4d2320d3193bdabb2d75e79793af7c3eb139e4f569f16f', 'sha256:011233e0c42a4a7836498e98c1acf5e744c96a67dd5032a6f666cc1fb97eab97', 'sha256:12875d118f21cf35604176872447cdb57b07126750a33748bac15e77f90f1f9c', 'sha256:b5b3f092fe345c03bca1e0b687dfbb39364b21ebb8ba90e3fa707374b7915204', 'sha256:528a2a692c65dd5cafc130de286030af251d2ee0483a5bf50c9348aefe834e8a', 'sha256:718856856ba31f14f13ba885ff13874be7fefc53984d2832458f12c38205f7f7', 'sha256:f25ed6e28ddf50de7e7ea99d7a976d6a9c415f03adcaac9c41ff6ff41b6d86ac', 'sha256:d21237d0cd37acded35154e29aec853e945950321dd2ffd1a7d86fe686814669', 'sha256:80ca33961ced9c63358056bd08403ff866512038883e74f3a4bf88ad3eb66838', 'sha256:81c4b81611e3a3cb30e59b0cf05b888c675f97e3adb2c8672c3154047980726b'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=pillow, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===9.0.1, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=pillow==9.0.1)>, _ireq=None)]\n Package installation failed...\n\u001b[0mRemoving intermediate container a06330836830\n","stderr":"The command '/bin/sh -c pip install pipenv && pipenv install --system' returned a non-zero code: 1\n"}}