{"repository":"https://github.com/ddurko1950/flan-scan","dockerfilePath":"Dockerfile","startTime":1672916236208,"endTime":1672916315031,"clone":{"startTime":1672916236208,"stdout":"","stderr":"Cloning into '/tmp/dinghy-analysis/ddurko1950/flan-scan'...\n","error":null,"endTime":1672916236917,"commit":"0c3f6722038a7c2b21bcbf902a5652006d88e0f1"},"originalBuild":{"startTime":1672916236991,"endTime":1672916314970,"error":{"code":1,"killed":false,"signal":null,"cmd":"docker build --no-cache --force-rm -t flan-scan:latest -f /tmp/dinghy-analysis/ddurko1950/flan-scan/Dockerfile ."},"stdout":"Sending build context to Docker daemon  121.3kB\r\r\nStep 1/9 : FROM python:3.5-alpine\n3.5-alpine: Pulling from library/python\ndf20fa9351a1: Already exists\n36b3adc4ff6f: Pulling fs layer\n0c2f653029e6: Pulling fs layer\n62f59dc43a4a: Pulling fs layer\nba334520d4fe: Pulling fs layer\nba334520d4fe: Waiting\n36b3adc4ff6f: Verifying Checksum\n36b3adc4ff6f: Download complete\n62f59dc43a4a: Download complete\n0c2f653029e6: Verifying Checksum\n0c2f653029e6: Download complete\nba334520d4fe: Download complete\n36b3adc4ff6f: Pull complete\n0c2f653029e6: Pull complete\n62f59dc43a4a: Pull complete\nba334520d4fe: Pull complete\nDigest: sha256:179992e913f024340db6347446966f69c153de72ad440b72bf7418c940c8692a\nStatus: Downloaded newer image for python:3.5-alpine\n ---> 6d034ccc54a2\nStep 2/9 : RUN apk add nmap nmap-scripts git\n ---> Running in 7dfd6a899a3e\nfetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz\nfetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz\n(1/13) Installing nghttp2-libs (1.41.0-r0)\n(2/13) Installing libcurl (7.79.1-r1)\n(3/13) Installing pcre2 (10.35-r0)\n(4/13) Installing git (2.26.3-r1)\n(5/13) Installing libgcc (9.3.0-r2)\n(6/13) Installing lua5.3-libs (5.3.5-r6)\n(7/13) Installing libpcap (1.9.1-r2)\n(8/13) Installing pcre (8.44-r0)\n(9/13) Installing libssh2 (1.9.0-r1)\n(10/13) Installing libstdc++ (9.3.0-r2)\n(11/13) Installing nmap (7.80-r2)\n(12/13) Installing nmap-nselibs (7.80-r2)\n(13/13) Installing nmap-scripts (7.80-r2)\nExecuting busybox-1.31.1-r16.trigger\nOK: 51 MiB in 38 packages\nRemoving intermediate container 7dfd6a899a3e\n ---> 4cd26340c88d\nStep 3/9 : RUN pip install xmltodict google-cloud-storage boto3\n ---> Running in d52a581b287a\n\u001b[91mDEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.\n\u001b[0mCollecting xmltodict\n  Downloading xmltodict-0.13.0-py2.py3-none-any.whl (10.0 kB)\nCollecting google-cloud-storage\n  Downloading google_cloud_storage-1.32.0-py2.py3-none-any.whl (92 kB)\nCollecting boto3\n  Downloading boto3-1.16.63-py2.py3-none-any.whl (130 kB)\nCollecting google-auth<2.0dev,>=1.11.0\n  Downloading google_auth-1.23.0-py2.py3-none-any.whl (114 kB)\nCollecting requests<3.0.0dev,>=2.18.0\n  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)\nCollecting google-cloud-core<2.0dev,>=1.4.1\n  Downloading google_cloud_core-1.4.4-py2.py3-none-any.whl (27 kB)\nCollecting google-resumable-media<2.0dev,>=1.0.0\n  Downloading google_resumable_media-1.1.0-py2.py3-none-any.whl (75 kB)\nCollecting botocore<1.20.0,>=1.19.63\n  Downloading botocore-1.19.63-py2.py3-none-any.whl (7.2 MB)\nCollecting s3transfer<0.4.0,>=0.3.0\n  Downloading s3transfer-0.3.7-py2.py3-none-any.whl (73 kB)\nCollecting jmespath<1.0.0,>=0.7.1\n  Downloading jmespath-0.10.0-py2.py3-none-any.whl (24 kB)\nCollecting cachetools<5.0,>=2.0.0\n  Downloading cachetools-4.2.4-py3-none-any.whl (10 kB)\nCollecting pyasn1-modules>=0.2.1\n  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)\nCollecting rsa<5,>=3.1.4; python_version >= \"3.5\"\n  Downloading rsa-4.7.2-py3-none-any.whl (34 kB)\nCollecting six>=1.9.0\n  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)\nRequirement already satisfied: setuptools>=40.3.0 in /usr/local/lib/python3.5/site-packages (from google-auth<2.0dev,>=1.11.0->google-cloud-storage) (50.3.0)\nCollecting idna<3,>=2.5\n  Downloading idna-2.10-py2.py3-none-any.whl (58 kB)\nCollecting urllib3<1.27,>=1.21.1\n  Downloading urllib3-1.26.9-py2.py3-none-any.whl (138 kB)\nCollecting certifi>=2017.4.17\n  Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)\nCollecting chardet<5,>=3.0.2\n  Downloading chardet-4.0.0-py2.py3-none-any.whl (178 kB)\nCollecting google-api-core<2.0.0dev,>=1.21.0\n  Downloading google_api_core-1.23.0-py2.py3-none-any.whl (91 kB)\nCollecting google-crc32c<2.0dev,>=1.0; python_version >= \"3.5\"\n  Downloading google-crc32c-1.0.0.tar.gz (10 kB)\n  Installing build dependencies: started\n  Installing build dependencies: finished with status 'done'\n  Getting requirements to build wheel: started\n  Getting requirements to build wheel: finished with status 'done'\n  Installing backend dependencies: started\n  Installing backend dependencies: finished with status 'error'\n\u001b[91m  ERROR: Command errored out with exit status 1:\n   command: /usr/local/bin/python /usr/local/lib/python3.5/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-gx5bf93u/normal --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'cffi>=1.0.0'\n       cwd: None\n  Complete output (123 lines):\n  DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.\n  Collecting cffi>=1.0.0\n    Downloading cffi-1.15.1.tar.gz (508 kB)\n  Collecting pycparser\n    Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)\n  Building wheels for collected packages: cffi\n    Building wheel for cffi (setup.py): started\n    Building wheel for cffi (setup.py): finished with status 'error'\n    ERROR: Command errored out with exit status 1:\n     command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-ixcey8yb/cffi/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-ixcey8yb/cffi/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' bdist_wheel -d /tmp/pip-wheel-hgywx_bd\n         cwd: /tmp/pip-install-ixcey8yb/cffi/\n    Complete output (48 lines):\n    unable to execute 'gcc': No such file or directory\n    unable to execute 'gcc': No such file or directory\n  \n        No working compiler found, or bogus compiler options passed to\n        the compiler from Python's standard \"distutils\" module.  See\n        the error messages above.  Likely, the problem is not related\n        to CFFI but generic to the setup.py of any Python package that\n        tries to compile C code.  (Hints: on OS/X 10.8, for errors about\n        -mno-fused-madd see http://stackoverflow.com/questions/22313407/\n        Otherwise, see https://wiki.python.org/moin/CompLangPython or\n        the IRC channel #python on irc.libera.chat.)\n  \n        Trying to continue anyway.  If you are trying to install CFFI from\n        a build done in a different context, you can ignore this warning.\n  \n    running bdist_wheel\n    running build\n    running build_py\n    creating build\n    creating build/lib.linux-x86_64-3.5\n    creating build/lib.linux-x86_64-3.5/cffi\n    copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/verifier.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/api.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/__init__.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/recompiler.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/error.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/commontypes.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/lock.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/model.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/cparser.py -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/_embedding.h -> build/lib.linux-x86_64-3.5/cffi\n    copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.5/cffi\n    running build_ext\n    building '_cffi_backend' extension\n    creating build/temp.linux-x86_64-3.5\n    creating build/temp.linux-x86_64-3.5/c\n    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DFFI_BUILDING=1 -I/usr/include/ffi -I/usr/include/libffi -I/usr/local/include/python3.5m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.5/c/_cffi_backend.o\n    unable to execute 'gcc': No such file or directory\n    error: command 'gcc' failed with exit status 1\n    ----------------------------------------\n    ERROR: Failed building wheel for cffi\n    Running setup.py clean for cffi\n  Failed to build cffi\n  Installing collected packages: pycparser, cffi\n      Running setup.py install for cffi: started\n      Running setup.py install for cffi: finished with status 'error'\n      ERROR: Command errored out with exit status 1:\n       command: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-ixcey8yb/cffi/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-ixcey8yb/cffi/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /tmp/pip-record-nrfcfhwa/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-gx5bf93u/normal --compile --install-headers /tmp/pip-build-env-gx5bf93u/normal/include/python3.5m/cffi\n           cwd: /tmp/pip-install-ixcey8yb/cffi/\n      Complete output (48 lines):\n      unable to execute 'gcc': No such file or directory\n      unable to execute 'gcc': No such file or directory\n  \n          No working compiler found, or bogus compiler options passed to\n          the compiler from Python's standard \"distutils\" module.  See\n          the error messages above.  Likely, the problem is not related\n          to CFFI but generic to the setup.py of any Python package that\n          tries to compile C code.  (Hints: on OS/X 10.8, for errors about\n          -mno-fused-madd see http://stackoverflow.com/questions/22313407/\n          Otherwise, see https://wiki.python.org/moin/CompLangPython or\n          the IRC channel #python on irc.libera.chat.)\n  \n          Trying to continue anyway.  If you are trying to install CFFI from\n          a build done in a different context, you can ignore this warning.\n  \n      running install\n      running build\n      running build_py\n      creating build\n      creating build/lib.linux-x86_64-3.5\n      creating build/lib.linux-x86_64-3.5/cffi\n      copying cffi/ffiplatform.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/verifier.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/api.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/__init__.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/recompiler.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/pkgconfig.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/error.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/commontypes.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/vengine_gen.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/lock.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/model.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/cparser.py -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/_cffi_include.h -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/parse_c_type.h -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/_embedding.h -> build/lib.linux-x86_64-3.5/cffi\n      copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-3.5/cffi\n      running build_ext\n      building '_cffi_backend' extension\n      creating build/temp.linux-x86_64-3.5\n      creating build/temp.linux-x86_64-3.5/c\n      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DFFI_BUILDING=1 -I/usr/include/ffi -I/usr/include/libffi -I/usr/local/include/python3.5m -c c/_cffi_backend.c -o build/temp.linux-x86_64-3.5/c/_cffi_backend.o\n      unable to execute 'gcc': No such file or directory\n      error: command 'gcc' failed with exit status 1\n      ----------------------------------------\n  ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/tmp/pip-install-ixcey8yb/cffi/setup.py'\"'\"'; __file__='\"'\"'/tmp/pip-install-ixcey8yb/cffi/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' install --record /tmp/pip-record-nrfcfhwa/install-record.txt --single-version-externally-managed --prefix /tmp/pip-build-env-gx5bf93u/normal --compile --install-headers /tmp/pip-build-env-gx5bf93u/normal/include/python3.5m/cffi Check the logs for full command output.\n  WARNING: You are using pip version 20.2.3; however, version 20.3.4 is available.\n  You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.\n  ----------------------------------------\n\u001b[0m\u001b[91mERROR: Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.5/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-gx5bf93u/normal --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'cffi>=1.0.0' Check the logs for full command output.\n\u001b[0m\u001b[91mWARNING: You are using pip version 20.2.3; however, version 20.3.4 is available.\nYou should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.\n\u001b[0mRemoving intermediate container d52a581b287a\n","stderr":"The command '/bin/sh -c pip install xmltodict google-cloud-storage boto3' returned a non-zero code: 1\n"}}