{"repository":"https://github.com/tsoporan/fittrak","dockerfilePath":"Dockerfile","startTime":1672590117598,"clone":{"stdout":"","stderr":"Cloning into '/tmp/dinghy-analysis/tsoporan/fittrak'...\n","error":null,"commit":"00ab733c81e5e18b74223e0fe501c0c8df585f41"},"originalBuild":{"startTimestamp":1672590118551,"endTimestamp":1672590247255,"error":{"code":1,"killed":false,"signal":null,"cmd":"docker build --no-cache --force-rm -t fittrak:latest -f /tmp/dinghy-analysis/tsoporan/fittrak/Dockerfile ."},"stdout":"Sending build context to Docker daemon  1.384MB\r\r\nStep 1/8 : FROM python:3\n ---> 75cc8d87cc34\nStep 2/8 : ENV PYTHONUNBUFFERED=1\n ---> Running in bf822ab4227f\nRemoving intermediate container bf822ab4227f\n ---> 869a449dc837\nStep 3/8 : WORKDIR /usr/src/app\n ---> Running in 3ec75b3df23e\nRemoving intermediate container 3ec75b3df23e\n ---> 589ce987ed6c\nStep 4/8 : RUN apt-get update   && apt-get install postgresql-client -y   && pip install pip -U   && pip install pipenv\n ---> Running in 0a41617b5d0b\nGet:1 http://deb.debian.org/debian bullseye InRelease [116 kB]\nGet:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]\nGet:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]\nGet:4 http://deb.debian.org/debian bullseye/main amd64 Packages [8183 kB]\nGet:5 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [210 kB]\nGet:6 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [14.6 kB]\nFetched 8616 kB in 2s (5165 kB/s)\nReading package lists...\nReading package lists...\nBuilding dependency tree...\nReading state information...\nThe following additional packages will be installed:\n  postgresql-client-13 postgresql-client-common\nSuggested packages:\n  postgresql-13 postgresql-doc-13\nThe following NEW packages will be installed:\n  postgresql-client postgresql-client-13 postgresql-client-common\n0 upgraded, 3 newly installed, 0 to remove and 1 not upgraded.\nNeed to get 1662 kB of archives.\nAfter this operation, 6879 kB of additional disk space will be used.\nGet:1 http://deb.debian.org/debian bullseye/main amd64 postgresql-client-common all 225 [89.3 kB]\nGet:2 http://deb.debian.org/debian bullseye/main amd64 postgresql-client-13 amd64 13.9-0+deb11u1 [1508 kB]\nGet:3 http://deb.debian.org/debian bullseye/main amd64 postgresql-client all 13+225 [64.8 kB]\n\u001b[91mdebconf: delaying package configuration, since apt-utils is not installed\n\u001b[0mFetched 1662 kB in 0s (15.1 MB/s)\nSelecting previously unselected package postgresql-client-common.\r\n(Reading database ... \r(Reading database ... 5%\r(Reading database ... 10%\r(Reading database ... 15%\r(Reading database ... 20%\r(Reading database ... 25%\r(Reading database ... 30%\r(Reading database ... 35%\r(Reading database ... 40%\r(Reading database ... 45%\r(Reading database ... 50%\r(Reading database ... 55%\r(Reading database ... 60%\r(Reading database ... 65%\r(Reading database ... 70%\r(Reading database ... 75%\r(Reading database ... 80%\r(Reading database ... 85%\r(Reading database ... 90%\r(Reading database ... 95%\r(Reading database ... 100%\r(Reading database ... 23422 files and directories currently installed.)\r\nPreparing to unpack .../postgresql-client-common_225_all.deb ...\r\nUnpacking postgresql-client-common (225) ...\r\nSelecting previously unselected package postgresql-client-13.\r\nPreparing to unpack .../postgresql-client-13_13.9-0+deb11u1_amd64.deb ...\r\nUnpacking postgresql-client-13 (13.9-0+deb11u1) ...\r\nSelecting previously unselected package postgresql-client.\r\nPreparing to unpack .../postgresql-client_13+225_all.deb ...\r\nUnpacking postgresql-client (13+225) ...\r\nSetting up postgresql-client-common (225) ...\r\nSetting up postgresql-client-13 (13.9-0+deb11u1) ...\r\nupdate-alternatives: using /usr/share/postgresql/13/man/man1/psql.1.gz to provide /usr/share/man/man1/psql.1.gz (psql.1.gz) in auto mode\r\nSetting up postgresql-client (13+225) ...\r\nRequirement already satisfied: pip in /usr/local/lib/python3.11/site-packages (22.3.1)\n\u001b[91mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\n\u001b[0mCollecting pipenv\n  Downloading pipenv-2022.12.19-py3-none-any.whl (2.9 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 38.8 MB/s eta 0:00:00\nCollecting certifi\n  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 1.1 MB/s eta 0:00:00\nRequirement already satisfied: setuptools>=36.2.1 in /usr/local/lib/python3.11/site-packages (from pipenv) (65.5.0)\nCollecting virtualenv-clone>=0.2.5\n  Downloading virtualenv_clone-0.5.7-py3-none-any.whl (6.6 kB)\nCollecting virtualenv\n  Downloading virtualenv-20.17.1-py3-none-any.whl (8.8 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 48.2 MB/s eta 0:00:00\nCollecting distlib<1,>=0.3.6\n  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.5/468.5 kB 19.5 MB/s eta 0:00:00\nCollecting filelock<4,>=3.4.1\n  Downloading filelock-3.9.0-py3-none-any.whl (9.7 kB)\nCollecting platformdirs<3,>=2.4\n  Downloading platformdirs-2.6.2-py3-none-any.whl (14 kB)\nInstalling collected packages: distlib, virtualenv-clone, platformdirs, filelock, certifi, virtualenv, pipenv\nSuccessfully installed certifi-2022.12.7 distlib-0.3.6 filelock-3.9.0 pipenv-2022.12.19 platformdirs-2.6.2 virtualenv-20.17.1 virtualenv-clone-0.5.7\n\u001b[91mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\n\u001b[0mRemoving intermediate container 0a41617b5d0b\n ---> 4a848520ab3d\nStep 5/8 : COPY Pipfile Pipfile.lock . ./\n ---> f38534a273a2\nStep 6/8 : RUN pipenv install --system --ignore-pipfile\n ---> Running in 1c5d57af63ef\nInstalling dependencies from Pipfile.lock (ff1d15)...\n\u001b[91mAn error occurred while installing aniso8601==6.0.0 --hash=sha256:b8a6a9b24611fc50cf2d9b45d371bfdc4fd0581d1cc52254f5502130a776d4af --hash=sha256:bb167645c79f7a438f9dfab6161af9bed75508c645b1f07d1158240841d22673! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing certifi==2019.6.16 --hash=sha256:046832c04d4e752f37383b628bc601a7ea7211496b4638f6514d0e5b9acc4939 --hash=sha256:945e3ba63a0b9f577b1395204e13c3a231f9bc0223888be653286534e5873695! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing chardet==3.0.4 --hash=sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae --hash=sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing defusedxml==0.6.0 --hash=sha256:f684034d135af4c6cbb949b8a4d2ed61634515257a67299e5f940fbaa34377f5 --hash=sha256:6687150770438374ab581bb7a1b327a847dd9c5749e396102de3fad4e8a3ef93! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django==2.2.4 --hash=sha256:16a5d54411599780ac9dfe3b9b38f90f785c51259a584e0b24b6f14a7f69aae8 --hash=sha256:9a2f98211ab474c710fcdad29c82f30fc14ce9917c7a70c3682162a624de4035! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django-allauth==0.39.1 --hash=sha256:4444434c2f43188e16e0a7732c3638e12787ca7e5032f69b6d30b2912f53809e! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django-allow-cidr==0.3.1 --hash=sha256:d9a3b22c14e91c26ddd010c278ddf7e2c69a5421c862a3a3cd448ae57fd833e8 --hash=sha256:e8708c0511a78b80d9b74f718ee46685a1425e6d3520143bd00c773fdca56cc7! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django-cors-headers==3.0.2 --hash=sha256:5b80bf0f8d7fc6e2bcb4f40781d5ff3661961bbf1982e52daec77241dea3b890 --hash=sha256:ebf3e2cf25aa6993b959a8e6a87828ebb3c8fe5bc3ec4a2d6e65f3b8d9b4212c! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django-extensions==2.2.1 --hash=sha256:8a2552fdeb222b23895ef52cdc28fc56efba976f6da07ca92937f6f5e626e345 --hash=sha256:4aafdb865104eaa5d681b9976b36c52c9d441be89b7d782e40808f1c5c0c8f93! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django-filter==2.2.0 --hash=sha256:558c727bce3ffa89c4a7a0b13bc8976745d63e5fd576b3a9a851650ef11c401b --hash=sha256:c3deb57f0dd7ff94d7dce52a047516822013e2b441bed472b722a317658cfd14! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django-graphql-jwt==0.2.1 --hash=sha256:6dcf9dd4990098e289d76ab4220edbf436a2e26dc6af1d4a526ac699ad93bf14! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django-webpack-loader==0.6.0 --hash=sha256:970b968c2a8975fb7eff56a3bab5d0d90d396740852d1e0c50c5cfe2b824199a --hash=sha256:60bab6b9a037a5346fad12d2a70a6bc046afb33154cf75ed640b93d3ebd5f520! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing graphene==2.1.7 --hash=sha256:77d61618132ccd084c343e64c22d806cee18dce73cc86e0f427378dbdeeac287 --hash=sha256:acf808d50d053b94f7958414d511489a9e490a7f9563b9be80f6875fc5723d2a! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing graphene-django==2.4.0 --hash=sha256:5714c5dd1200800ddc12d0782b0d82db70aedf387575e5b57ee2cdee4f25c681 --hash=sha256:3101e8a8353c6b13f33261f5b0437deb3d3614d1c44b2d56932b158e3660c0cd! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing graphql-core==2.2.1 --hash=sha256:da64c472d720da4537a2e8de8ba859210b62841bd47a9be65ca35177f62fe0e4 --hash=sha256:1488f2a5c2272dc9ba66e3042a6d1c30cea0db4c80bd1e911c6791ad6187d91b! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing graphql-relay==2.0.0 --hash=sha256:0e94201af4089e1f81f07d7bd8f84799768e39d70fa1ea16d1df505b46cc6335 --hash=sha256:75aa0758971e252964cb94068a4decd472d2a8295229f02189e3cbca1f10dbb5 --hash=sha256:7fa74661246e826ef939ee92e768f698df167a7617361ab399901eaebf80dce6! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing gunicorn==19.9.0 --hash=sha256:aa8e0b40b4157b36a5df5e599f45c9c76d6af43845ba3b3b0efe2c70473c2471 --hash=sha256:fa2662097c66f920f53f70621c6c58ca4a3c4d3434205e608e121b5b3b71f4f3! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing hashids==1.2.0 --hash=sha256:6539b892a426e75747a9c0ad69409e9566f9c21b79310fc3424b5b6726f28da6! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing idna==2.8 --hash=sha256:ea8b7f6188e6fa117537c3df7da9fc686d485087abf6ac197f9c46432f7e4a3c --hash=sha256:c357b3f628cf53ae2c4c05627ecc484553142ca23264e593d327bcde5e9c3407! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing netaddr==0.7.19 --hash=sha256:56b3558bd71f3f6999e4c52e349f38660e54a7a8a9943335f73dfc96883e08ca --hash=sha256:38aeec7cdd035081d3a4c306394b19d677623bf76fa0913f6695127c7753aefd! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing oauthlib==3.0.2 --hash=sha256:b4d99ae8ccfb7d33ba9591b59355c64eef5241534aa3da2e4c0435346b84bc8e --hash=sha256:40a63637707e9163eda62d0f5345120c65e001a790480b8256448543c1f78f66! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing promise==2.2.1 --hash=sha256:348f5f6c3edd4fd47c9cd65aed03ac1b31136d375aa63871a57d3e444c85655c --hash=sha256:2ebbfc10b7abf6354403ed785fe4f04b9dfd421eb1a474ac8d187022228332af! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing psycopg2-binary==2.8.3 --hash=sha256:d17e3054b17e1a6cb8c1140f76310f6ede811e75b7a9d461922d2c72973f583e --hash=sha256:af39d0237b17d0a5a5f638e9dffb34013ce2b1d41441fd30283e42b22d16858a --hash=sha256:f78e8b487de4d92640105c1389e5b90be3496b1d75c90a666edd8737cc2dbab7 --hash=sha256:d305313c5a9695f40c46294d4315ed3a07c7d2b55e48a9010dad7db7a66c8b7f --hash=sha256:2b6d561193f0dc3f50acfb22dd52ea8c8dfbc64bcafe3938b5f209cc17cb6f00 --hash=sha256:19d013e7b0817087517a4b3cab39c084d78898369e5c46258aab7be4f233d6a1 --hash=sha256:63c1b66e3b2a3a336288e4bcec499e0dc310cd1dceaed1c46fa7419764c68877 --hash=sha256:3eb70bb697abbe86b1d2b1316370c02ba320bfd1e9e35cf3b9566a855ea8e4e5 --hash=sha256:249b6b21ae4eb0f7b8423b330aa80fab5f821b9ffc3f7561a5e2fd6bb142cf5d --hash=sha256:8dbff4557bbef963697583366400822387cccf794ccb001f1f2307ed21854c68 --hash=sha256:5b3581319a3951f1e866f4f6c5e42023db0fae0284273b82e97dfd32c51985cd --hash=sha256:110457be80b63ff4915febb06faa7be002b93a76e5ba19bf3f27636a2ef58598 --hash=sha256:dd0ef0eb1f7dd18a3f4187226e226a7284bda6af5671937a221766e6ef1ee88f --hash=sha256:f0d43828003c82dbc9269de87aa449e9896077a71954fbbb10a614c017e65737 --hash=sha256:51a2fc7e94b98bd1bb5d4570936f24fc2b0541b63eccadf8fdea266db8ad2f70 --hash=sha256:52f1bdafdc764b7447e393ed39bb263eccb12bfda25a4ac06d82e3a9056251f6 --hash=sha256:2bd23e242e954214944481124755cbefe7c2cf563b1a54cd8d196d502f2578bf --hash=sha256:b2ecac57eb49e461e86c092761e6b8e1fd9654dbaaddf71a076dcc869f7014e2 --hash=sha256:af51bb9f055a3f4af0187149a8f60c9d516cf7d5565b3dac53358796a8fb2a5b --hash=sha256:3e1239242ca60b3725e65ab2f13765fc199b03af9eaf1b5572f0e97bdcee5b43 --hash=sha256:e1adff53b56db9905db48a972fb89370ad5736e0450b96f91bcf99cadd96cfd7 --hash=sha256:171352a03b22fc099f15103959b52ee77d9a27e028895d7e5fde127aa8e3bac5 --hash=sha256:080c72714784989474f97be9ab0ddf7b2ad2984527e77f2909fcd04d4df53809 --hash=sha256:85e699fcabe7f817c0f0a412d4e7c6627e00c412b418da7666ff353f38e30f67 --hash=sha256:cd37cc170678a4609becb26b53a2bc1edea65177be70c48dd7b39a1149cabd6e --hash=sha256:908d21d08d6b81f1b7e056bbf40b2f77f8c499ab29e64ec5113052819ef1c89b --hash=sha256:8123a99f24ecee469e5c1339427bcdb2a33920a18bb5c0d58b7c13f3b0298ba3 --hash=sha256:2ac0731d2d84b05c7bb39e85b7e123c3a0acd4cda631d8d542802c88deb9e87e! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing pyjwt==1.7.1 --hash=sha256:8d59a976fb773f3e6a39c85636357c4f0e242707394cadadd9814f5cbaa20e96 --hash=sha256:5c6eca3c2940464d106b99ba83b00c6add741c9becaec087fb7ccdefea71350e! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing python3-openid==3.1.0 --hash=sha256:0086da6b6ef3161cfe50fb1ee5cceaf2cda1700019fda03c2c5c440ca6abe4fa --hash=sha256:628d365d687e12da12d02c6691170f4451db28d6d68d050007e4a40065868502! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing pytz==2019.2 --hash=sha256:26c0b32e437e54a18161324a2fca3c4b9846b74a8dccddd843113109e1116b32 --hash=sha256:c894d57500a4cd2d5c71114aaab77dbab5eabd9022308ce5ac9bb93a60a6f0c7! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing requests==2.22.0 --hash=sha256:11e007a8a2aa0323f5a921e9e6a2d7e4e67d9877e85773fba9ba6419025cbeb4 --hash=sha256:9cf5292fcd0f598c671cfc1e0d7d1a7f13bb8085e9a590f48c010551dc6c4b31! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing requests-oauthlib==1.2.0 --hash=sha256:d3ed0c8f2e3bbc6b344fa63d6f933745ab394469da38db16bdddb461c7e25140 --hash=sha256:bd6533330e8748e94bf0b214775fed487d309b8b8fe823dc45641ebcd9a32f57! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing rx==1.6.1 --hash=sha256:7357592bc7e881a95e0c2013b73326f704953301ab551fbc8133a6fadab84105 --hash=sha256:13a1d8d9e252625c173dc795471e614eadfe1cf40ffc684e08b8fff0d9748c23! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing sentry-sdk==0.10.2 --hash=sha256:d491aa6399eaa3eded433972751a9770180730fd8b4c225b0b7f49c4fa2af70b --hash=sha256:d68003cdffbbfcadaa2c445b72e1050b0a44406f94199866f192986c016b23f5! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing singledispatch==3.4.0.3 --hash=sha256:5b06af87df13818d14f08a028e42f566640aef80805c3b50c5056b086e3c2b9c --hash=sha256:833b46966687b3de7f438c761ac475213e53b306740f1abfaa86e1d1aae56aa8! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing six==1.12.0 --hash=sha256:d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73 --hash=sha256:3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing sqlparse==0.3.0 --hash=sha256:7c3dca29c022744e95b547e867cee89f4fce4373f3549ccd8797d8eb52cdb873 --hash=sha256:40afe6b8d4b1117e7dff5504d7a8ce07d9a1b15aeeade8a2d10f130a834f8177! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing urllib3==1.25.3 --hash=sha256:b246607a25ac80bedac05c6f282e3cdaf3afb65420fd024ac94435cabe6e18d1 --hash=sha256:dbe59173209418ae49d485b87d1681aefa36252ee85884c31346debd19463232! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing werkzeug==0.15.5 --hash=sha256:a13b74dd3c45f758d4ebdb224be8f1ab8ef58b3c0ffc1783a8c7d9f4f50227e6 --hash=sha256:87ae4e5b5366da2347eb3116c0e6c681a0e939a33b2805e2c0cbd282664932c4! Will try again.\n\u001b[0mInstalling initially failed dependencies...\n\u001b[91m[pipenv.exceptions.InstallError]: Looking in indexes: https://pypi.python.org/simple\n[pipenv.exceptions.InstallError]: Collecting defusedxml==0.6.0\n[pipenv.exceptions.InstallError]:   Using cached defusedxml-0.6.0-py2.py3-none-any.whl (23 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting django==2.2.4\n[pipenv.exceptions.InstallError]:   Using cached Django-2.2.4-py3-none-any.whl (7.5 MB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting django-cors-headers==3.0.2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached django_cors_headers-3.0.2-py2.py3-none-any.whl (13 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting django-filter==2.2.0\n[pipenv.exceptions.InstallError]:   Using cached django_filter-2.2.0-py3-none-any.whl (69 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting gunicorn==19.9.0\n[pipenv.exceptions.InstallError]:   Using cached gunicorn-19.9.0-py2.py3-none-any.whl (112 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting idna==2.8\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached idna-2.8-py2.py3-none-any.whl (58 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting oauthlib==3.0.2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached oauthlib-3.0.2-py2.py3-none-any.whl (143 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting psycopg2-binary==2.8.3\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached psycopg2-binary-2.8.3.tar.gz (378 kB)\n[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Building wheels for collected packages: psycopg2-binary\n[pipenv.exceptions.InstallError]:   Building wheel for psycopg2-binary (setup.py): started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Building wheel for psycopg2-binary (setup.py): finished with status 'error'\n[pipenv.exceptions.InstallError]:   Running setup.py clean for psycopg2-binary\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Failed to build psycopg2-binary\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Installing collected packages: psycopg2-binary, oauthlib, idna, gunicorn, django-filter, django-cors-headers, django, defusedxml\n[pipenv.exceptions.InstallError]:   Running setup.py install for psycopg2-binary: started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Running setup.py install for psycopg2-binary: finished with status 'error'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: error: subprocess-exited-with-error\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   × python setup.py bdist_wheel did not run successfully.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   │ exit code: 1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   ╰─> [73 lines of output]\n[pipenv.exceptions.InstallError]:       /usr/local/lib/python3.11/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         warnings.warn(msg, warning_class)\n[pipenv.exceptions.InstallError]:       running bdist_wheel\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build_py\n[pipenv.exceptions.InstallError]:       creating build\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-cpython-311\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/__init__.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/pool.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/_ipaddress.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n[pipenv.exceptions.InstallError]:       copying lib/errors.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/_json.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/sql.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n[pipenv.exceptions.InstallError]:       copying lib/_lru_cache.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/compat.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/_range.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n[pipenv.exceptions.InstallError]:       copying lib/tz.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/extras.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/extensions.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/errorcodes.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n[pipenv.exceptions.InstallError]:       warning: build_py: byte-compiling is disabled, skipping.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build_ext\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       building 'psycopg2._psycopg' extension\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/temp.linux-x86_64-cpython-311\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/temp.linux-x86_64-cpython-311/psycopg\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_asis.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_asis.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_binary.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_binary.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_datetime.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_datetime.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_list.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_list.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_pboolean.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_pboolean.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_pdecimal.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_pdecimal.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_pfloat.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_pfloat.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_pint.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_pint.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_qstring.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_qstring.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/bytes_format.c -o build/temp.linux-x86_64-cpython-311/psycopg/bytes_format.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/column_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/column_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/connection_int.c -o build/temp.linux-x86_64-cpython-311/psycopg/connection_int.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/connection_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/connection_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/conninfo_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/conninfo_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/cursor_int.c -o build/temp.linux-x86_64-cpython-311/psycopg/cursor_int.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/cursor_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/cursor_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/diagnostics_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/diagnostics_type.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/error_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/error_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/green.c -o build/temp.linux-x86_64-cpython-311/psycopg/green.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/libpq_support.c -o build/temp.linux-x86_64-cpython-311/psycopg/libpq_support.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/lobject_int.c -o build/temp.linux-x86_64-cpython-311/psycopg/lobject_int.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/lobject_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/lobject_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/microprotocols.c -o build/temp.linux-x86_64-cpython-311/psycopg/microprotocols.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/microprotocols_proto.c -o build/temp.linux-x86_64-cpython-311/psycopg/microprotocols_proto.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/notify_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/notify_type.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/pqpath.c -o build/temp.linux-x86_64-cpython-311/psycopg/pqpath.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-cpython-311/psycopg/psycopgmodule.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c: In function ‘add_module_types’:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c:920:36: error: lvalue required as left operand of assignment\n[pipenv.exceptions.InstallError]:         920 |         Py_TYPE(typetable[i].type) = &PyType_Type;\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |                                    ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c: In function ‘datetime_init’:\n[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c:952:30: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         952 |     Py_TYPE(&pydatetimeType) = &PyType_Type;\n[pipenv.exceptions.InstallError]:             |                              ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c: In function ‘PyInit__psycopg’:\n[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c:1084:28: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:        1084 |     Py_TYPE(&typecastType) = &PyType_Type;\n[pipenv.exceptions.InstallError]:             |                            ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c:1087:25: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:        1087 |     Py_TYPE(&chunkType) = &PyType_Type;\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |                         ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c:1090:25: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:        1090 |     Py_TYPE(&errorType) = &PyType_Type;\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |                         ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       error: command '/usr/bin/gcc' failed with exit code 1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       [end of output]\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.\n[pipenv.exceptions.InstallError]:   ERROR: Failed building wheel for psycopg2-binary\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   error: subprocess-exited-with-error\n[pipenv.exceptions.InstallError]:   \n[pipenv.exceptions.InstallError]:   × Running setup.py install for psycopg2-binary did not run successfully.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   │ exit code: 1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   ╰─> [75 lines of output]\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       /usr/local/lib/python3.11/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         warnings.warn(msg, warning_class)\n[pipenv.exceptions.InstallError]:       running install\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       /usr/local/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         warnings.warn(\n[pipenv.exceptions.InstallError]:       running build\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build_py\n[pipenv.exceptions.InstallError]:       creating build\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-cpython-311\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/__init__.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n[pipenv.exceptions.InstallError]:       copying lib/pool.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/_ipaddress.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n[pipenv.exceptions.InstallError]:       copying lib/errors.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/_json.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/sql.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n[pipenv.exceptions.InstallError]:       copying lib/_lru_cache.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/compat.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n[pipenv.exceptions.InstallError]:       copying lib/_range.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/tz.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/extras.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/extensions.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/errorcodes.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n[pipenv.exceptions.InstallError]:       warning: build_py: byte-compiling is disabled, skipping.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build_ext\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       building 'psycopg2._psycopg' extension\n[pipenv.exceptions.InstallError]:       creating build/temp.linux-x86_64-cpython-311\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/temp.linux-x86_64-cpython-311/psycopg\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_asis.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_asis.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_binary.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_binary.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_datetime.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_datetime.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_list.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_list.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_pboolean.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_pboolean.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_pdecimal.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_pdecimal.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_pfloat.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_pfloat.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_pint.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_pint.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_qstring.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_qstring.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/bytes_format.c -o build/temp.linux-x86_64-cpython-311/psycopg/bytes_format.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/column_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/column_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/connection_int.c -o build/temp.linux-x86_64-cpython-311/psycopg/connection_int.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/connection_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/connection_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/conninfo_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/conninfo_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/cursor_int.c -o build/temp.linux-x86_64-cpython-311/psycopg/cursor_int.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/cursor_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/cursor_type.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/diagnostics_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/diagnostics_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/error_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/error_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/green.c -o build/temp.linux-x86_64-cpython-311/psycopg/green.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/libpq_support.c -o build/temp.linux-x86_64-cpython-311/psycopg/libpq_support.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/lobject_int.c -o build/temp.linux-x86_64-cpython-311/psycopg/lobject_int.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/lobject_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/lobject_type.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/microprotocols.c -o build/temp.linux-x86_64-cpython-311/psycopg/microprotocols.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/microprotocols_proto.c -o build/temp.linux-x86_64-cpython-311/psycopg/microprotocols_proto.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/notify_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/notify_type.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/pqpath.c -o build/temp.linux-x86_64-cpython-311/psycopg/pqpath.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.3 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-cpython-311/psycopg/psycopgmodule.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c: In function ‘add_module_types’:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c:920:36: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         920 |         Py_TYPE(typetable[i].type) = &PyType_Type;\n[pipenv.exceptions.InstallError]:             |                                    ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c: In function ‘datetime_init’:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c:952:30: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         952 |     Py_TYPE(&pydatetimeType) = &PyType_Type;\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |                              ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c: In function ‘PyInit__psycopg’:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c:1084:28: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:        1084 |     Py_TYPE(&typecastType) = &PyType_Type;\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |                            ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c:1087:25: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:        1087 |     Py_TYPE(&chunkType) = &PyType_Type;\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |                         ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c:1090:25: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:        1090 |     Py_TYPE(&errorType) = &PyType_Type;\n[pipenv.exceptions.InstallError]:             |                         ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       error: command '/usr/bin/gcc' failed with exit code 1\n[pipenv.exceptions.InstallError]:       [end of output]\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   \n[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: error: legacy-install-failure\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: × Encountered error while trying to install package.\n[pipenv.exceptions.InstallError]: ╰─> psycopg2-binary\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: \n[pipenv.exceptions.InstallError]: note: This is an issue with the package mentioned above, not pip.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: hint: See above for output from the failure.\n\u001b[0m\u001b[91mERROR: Couldn't install package: [Requirement(_name='defusedxml', vcs=None, req=NamedRequirement(name='defusedxml', version='==0.6.0', req=Requirement.parse('defusedxml==0.6.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=defusedxml, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===0.6.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=defusedxml==0.6.0)>), markers=None, _specifiers='==0.6.0', index=None, editable=False, hashes=frozenset({'sha256:f684034d135af4c6cbb949b8a4d2ed61634515257a67299e5f940fbaa34377f5', 'sha256:6687150770438374ab581bb7a1b327a847dd9c5749e396102de3fad4e8a3ef93'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=defusedxml, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===0.6.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=defusedxml==0.6.0)>, _ireq=None), Requirement(_name='django', vcs=None, req=NamedRequirement(name='django', version='==2.2.4', req=Requirement.parse('django==2.2.4'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=django, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.2.4, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django==2.2.4)>), markers=None, _specifiers='==2.2.4', index='pypi', editable=False, hashes=frozenset({'sha256:16a5d54411599780ac9dfe3b9b38f90f785c51259a584e0b24b6f14a7f69aae8', 'sha256:9a2f98211ab474c710fcdad29c82f30fc14ce9917c7a70c3682162a624de4035'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=django, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.2.4, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django==2.2.4)>, _ireq=None), Requirement(_name='django-cors-headers', vcs=None, req=NamedRequirement(name='django-cors-headers', version='==3.0.2', req=Requirement.parse('django-cors-headers==3.0.2'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=django-cors-headers, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===3.0.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django-cors-headers==3.0.2)>), markers=None, _specifiers='==3.0.2', index='pypi', editable=False, hashes=frozenset({'sha256:5b80bf0f8d7fc6e2bcb4f40781d5ff3661961bbf1982e52daec77241dea3b890', 'sha256:ebf3e2cf25aa6993b959a8e6a87828ebb3c8fe5bc3ec4a2d6e65f3b8d9b4212c'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=django-cors-headers, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===3.0.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django-cors-headers==3.0.2)>, _ireq=None), Requirement(_name='django-filter', vcs=None, req=NamedRequirement(name='django-filter', version='==2.2.0', req=Requirement.parse('django-filter==2.2.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=django-filter, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.2.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django-filter==2.2.0)>), markers=None, _specifiers='==2.2.0', index='pypi', editable=False, hashes=frozenset({'sha256:558c727bce3ffa89c4a7a0b13bc8976745d63e5fd576b3a9a851650ef11c401b', 'sha256:c3deb57f0dd7ff94d7dce52a047516822013e2b441bed472b722a317658cfd14'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=django-filter, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.2.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django-filter==2.2.0)>, _ireq=None), Requirement(_name='gunicorn', vcs=None, req=NamedRequirement(name='gunicorn', version='==19.9.0', req=Requirement.parse('gunicorn==19.9.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=gunicorn, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===19.9.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=gunicorn==19.9.0)>), markers=None, _specifiers='==19.9.0', index='pypi', editable=False, hashes=frozenset({'sha256:aa8e0b40b4157b36a5df5e599f45c9c76d6af43845ba3b3b0efe2c70473c2471', 'sha256:fa2662097c66f920f53f70621c6c58ca4a3c4d3434205e608e121b5b3b71f4f3'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=gunicorn, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===19.9.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=gunicorn==19.9.0)>, _ireq=None), Requirement(_name='idna', vcs=None, req=NamedRequirement(name='idna', version='==2.8', req=Requirement.parse('idna==2.8'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=idna, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.8, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=idna==2.8)>), markers=None, _specifiers='==2.8', index=None, editable=False, hashes=frozenset({'sha256:ea8b7f6188e6fa117537c3df7da9fc686d485087abf6ac197f9c46432f7e4a3c', 'sha256:c357b3f628cf53ae2c4c05627ecc484553142ca23264e593d327bcde5e9c3407'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=idna, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.8, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=idna==2.8)>, _ireq=None), Requirement(_name='oauthlib', vcs=None, req=NamedRequirement(name='oauthlib', version='==3.0.2', req=Requirement.parse('oauthlib==3.0.2'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=oauthlib, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===3.0.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=oauthlib==3.0.2)>), markers=None, _specifiers='==3.0.2', index=None, editable=False, hashes=frozenset({'sha256:b4d99ae8ccfb7d33ba9591b59355c64eef5241534aa3da2e4c0435346b84bc8e', 'sha256:40a63637707e9163eda62d0f5345120c65e001a790480b8256448543c1f78f66'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=oauthlib, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===3.0.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=oauthlib==3.0.2)>, _ireq=None), Requirement(_name='psycopg2-binary', vcs=None, req=NamedRequirement(name='psycopg2-binary', version='==2.8.3', req=Requirement.parse('psycopg2-binary==2.8.3'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=psycopg2-binary, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.8.3, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=psycopg2-binary==2.8.3)>), markers=None, _specifiers='==2.8.3', index='pypi', editable=False, hashes=frozenset({'sha256:d17e3054b17e1a6cb8c1140f76310f6ede811e75b7a9d461922d2c72973f583e', 'sha256:af39d0237b17d0a5a5f638e9dffb34013ce2b1d41441fd30283e42b22d16858a', 'sha256:f78e8b487de4d92640105c1389e5b90be3496b1d75c90a666edd8737cc2dbab7', 'sha256:d305313c5a9695f40c46294d4315ed3a07c7d2b55e48a9010dad7db7a66c8b7f', 'sha256:2b6d561193f0dc3f50acfb22dd52ea8c8dfbc64bcafe3938b5f209cc17cb6f00', 'sha256:19d013e7b0817087517a4b3cab39c084d78898369e5c46258aab7be4f233d6a1', 'sha256:63c1b66e3b2a3a336288e4bcec499e0dc310cd1dceaed1c46fa7419764c68877', 'sha256:3eb70bb697abbe86b1d2b1316370c02ba320bfd1e9e35cf3b9566a855ea8e4e5', 'sha256:249b6b21ae4eb0f7b8423b330aa80fab5f821b9ffc3f7561a5e2fd6bb142cf5d', 'sha256:8dbff4557bbef963697583366400822387cccf794ccb001f1f2307ed21854c68', 'sha256:5b3581319a3951f1e866f4f6c5e42023db0fae0284273b82e97dfd32c51985cd', 'sha256:110457be80b63ff4915febb06faa7be002b93a76e5ba19bf3f27636a2ef58598', 'sha256:dd0ef0eb1f7dd18a3f4187226e226a7284bda6af5671937a221766e6ef1ee88f', 'sha256:f0d43828003c82dbc9269de87aa449e9896077a71954fbbb10a614c017e65737', 'sha256:51a2fc7e94b98bd1bb5d4570936f24fc2b0541b63eccadf8fdea266db8ad2f70', 'sha256:52f1bdafdc764b7447e393ed39bb263eccb12bfda25a4ac06d82e3a9056251f6', 'sha256:2bd23e242e954214944481124755cbefe7c2cf563b1a54cd8d196d502f2578bf', 'sha256:b2ecac57eb49e461e86c092761e6b8e1fd9654dbaaddf71a076dcc869f7014e2', 'sha256:af51bb9f055a3f4af0187149a8f60c9d516cf7d5565b3dac53358796a8fb2a5b', 'sha256:3e1239242ca60b3725e65ab2f13765fc199b03af9eaf1b5572f0e97bdcee5b43', 'sha256:e1adff53b56db9905db48a972fb89370ad5736e0450b96f91bcf99cadd96cfd7', 'sha256:171352a03b22fc099f15103959b52ee77d9a27e028895d7e5fde127aa8e3bac5', 'sha256:080c72714784989474f97be9ab0ddf7b2ad2984527e77f2909fcd04d4df53809', 'sha256:85e699fcabe7f817c0f0a412d4e7c6627e00c412b418da7666ff353f38e30f67', 'sha256:cd37cc170678a4609becb26b53a2bc1edea65177be70c48dd7b39a1149cabd6e', 'sha256:908d21d08d6b81f1b7e056bbf40b2f77f8c499ab29e64ec5113052819ef1c89b', 'sha256:8123a99f24ecee469e5c1339427bcdb2a33920a18bb5c0d58b7c13f3b0298ba3', 'sha256:2ac0731d2d84b05c7bb39e85b7e123c3a0acd4cda631d8d542802c88deb9e87e'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=psycopg2-binary, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.8.3, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=psycopg2-binary==2.8.3)>, _ireq=None)]\n Package installation failed...\n\u001b[0mRemoving intermediate container 1c5d57af63ef\n","stderr":"The command '/bin/sh -c pipenv install --system --ignore-pipfile' returned a non-zero code: 1\n"},"endTime":1672590247322}