{"repository":"https://github.com/hugodelahousse/turbot","dockerfilePath":"Dockerfile","startTime":1672816934331,"clone":{"stdout":"","stderr":"Cloning into '/tmp/dinghy-analysis/hugodelahousse/turbot'...\n","error":null,"commit":"ceffe9ef70165d74ea33aa8e5e0779b0901dc5fd"},"originalBuild":{"startTimestamp":1672816935255,"endTimestamp":1672817069924,"error":{"code":1,"killed":false,"signal":null,"cmd":"docker build --no-cache --force-rm -t turbot:latest -f /tmp/dinghy-analysis/hugodelahousse/turbot/Dockerfile ."},"stdout":"Sending build context to Docker daemon    279kB\r\r\nStep 1/7 : FROM python:3\n3: Pulling from library/python\nDigest: sha256:250990a809a15bb6a3e307fec72dead200c882c940523fb1694baa78eb0e47c6\nStatus: Downloaded newer image for python:3\n ---> 75cc8d87cc34\nStep 2/7 : RUN pip install pipenv\n ---> Running in 827bab40a4fc\nCollecting pipenv\n  Downloading pipenv-2022.12.19-py3-none-any.whl (2.9 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 26.6 MB/s eta 0:00:00\nCollecting certifi\n  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.3/155.3 kB 9.6 MB/s eta 0:00:00\nRequirement already satisfied: setuptools>=36.2.1 in /usr/local/lib/python3.11/site-packages (from pipenv) (65.5.0)\nCollecting virtualenv-clone>=0.2.5\n  Downloading virtualenv_clone-0.5.7-py3-none-any.whl (6.6 kB)\nCollecting virtualenv\n  Downloading virtualenv-20.17.1-py3-none-any.whl (8.8 MB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 52.5 MB/s eta 0:00:00\nCollecting distlib<1,>=0.3.6\n  Downloading distlib-0.3.6-py2.py3-none-any.whl (468 kB)\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 468.5/468.5 kB 8.1 MB/s eta 0:00:00\nCollecting filelock<4,>=3.4.1\n  Downloading filelock-3.9.0-py3-none-any.whl (9.7 kB)\nCollecting platformdirs<3,>=2.4\n  Downloading platformdirs-2.6.2-py3-none-any.whl (14 kB)\nInstalling collected packages: distlib, virtualenv-clone, platformdirs, filelock, certifi, virtualenv, pipenv\nSuccessfully installed certifi-2022.12.7 distlib-0.3.6 filelock-3.9.0 pipenv-2022.12.19 platformdirs-2.6.2 virtualenv-20.17.1 virtualenv-clone-0.5.7\n\u001b[91mWARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv\n\u001b[0mRemoving intermediate container 827bab40a4fc\n ---> b96bb1f2abc0\nStep 3/7 : WORKDIR /app\n ---> Running in e3ec463aacaa\nRemoving intermediate container e3ec463aacaa\n ---> 62d196160577\nStep 4/7 : COPY Pipfile Pipfile.lock ./\n ---> 5593ba44ec7a\nStep 5/7 : RUN set -ex && pipenv install --deploy --system\n ---> Running in 51522a2b3b3d\n\u001b[91m+ pipenv install --deploy --system\n\u001b[0mInstalling dependencies from Pipfile.lock (2eca19)...\n\u001b[91mAn error occurred while installing aiodns==2.0.0 --hash=sha256:815fdef4607474295d68da46978a54481dd1e7be153c7d60f9e72773cd38d77d --hash=sha256:aaa5ac584f40fe778013df0aa6544bf157799bd3f608364b451840ed2c8688de! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing aiohttp==3.5.4 --hash=sha256:6d5ec9b8948c3d957e75ea14d41e9330e1ac3fed24ec53766c780f82805140dc --hash=sha256:a25237abf327530d9561ef751eef9511ab56fd9431023ca6f4803f1994104d72 --hash=sha256:0155af66de8c21b8dba4992aaeeabf55503caefae00067a3b1139f86d0ec50ed --hash=sha256:87331d1d6810214085a50749160196391a712a13336cd02ce1c3ea3d05bcf8d5 --hash=sha256:09654a9eca62d1bd6d64aa44db2498f60a5c1e0ac4750953fdd79d5c88955e10 --hash=sha256:199f1d106e2b44b6dacdf6f9245493c7d716b01d0b7fbe1959318ba4dc64d1f5 --hash=sha256:b05bd85cc99b06740aad3629c2585bda7b83bd86e080b44ba47faf905fdf1300 --hash=sha256:9cddaff94c0135ee627213ac6ca6d05724bfe6e7a356e5e09ec57bd3249510f6 --hash=sha256:a97a516e02b726e089cffcde2eea0d3258450389bbac48cbe89e0f0b6e7b0366 --hash=sha256:cc619d974c8c11fe84527e4b5e1c07238799a8c29ea1c1285149170524ba9303 --hash=sha256:629102a193162e37102c50713e2e31dc9a2fe7ac5e481da83e5bb3c0cee700aa --hash=sha256:9a02a04bbe581c8605ac423ba3a74999ec9d8bce7ae37977a3d38680f5780b6d --hash=sha256:00d198585474299c9c3b4f1d5de1a576cc230d562abc5e4a0e81d71a20a6ca55 --hash=sha256:296f30dedc9f4b9e7a301e5cc963012264112d78a1d3094cd83ef148fdf33ca1 --hash=sha256:c2bec436a2b5dafe5eaeb297c03711074d46b6eb236d002c13c42f25c4a8ce9d --hash=sha256:d4392defd4648badaa42b3e101080ae3313e8f4787cb517efd3f5b8157eaefd6 --hash=sha256:acc89b29b5f4e2332d65cd1b7d10c609a75b88ef8925d487a611ca788432dfa4 --hash=sha256:a5cbd7157b0e383738b8e29d6e556fde8726823dae0e348952a61742b21aeb12 --hash=sha256:40d7ea570b88db017c51392349cf99b7aefaaddd19d2c78368aeb0bddde9d390 --hash=sha256:368ed312550bd663ce84dc4b032a962fcb3c7cae099dbbd48663afc305e3b939 --hash=sha256:9c4c83f4fa1938377da32bc2d59379025ceeee8e24b89f72fcbccd8ca22dc9bf --hash=sha256:e1c3c582ee11af7f63a34a46f0448fca58e59889396ffdae1f482085061a2889! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing async-timeout==3.0.1 --hash=sha256:4291ca197d287d274d0b6cb5d6f8f8f82d434ed288f962539ff18cc9012f9ea3 --hash=sha256:0c3c816a028d47f659d6ff5c745cb2acf1f966da1fe5c19c77a70282b25f4c5f! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing attrs==19.1.0 --hash=sha256:69c0dbf2ed392de1cb5ec704444b08a5ef81680a61cb899dc08127123af36a79 --hash=sha256:f0b870f674851ecbfbbbd364d6b5cbdff9dcedbc7f3f5e18a6891057f21fe399! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing certifi==2019.3.9 --hash=sha256:59b7658e26ca9c7339e00f8f4636cdfe59d34fa37b9b04f6f9e9926b3cece1a5 --hash=sha256:b26104d6835d1f5e49452a26eb2ff87fe7090b89dfcaee5ea2212697e1e1d7ae! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing cffi==1.12.3 --hash=sha256:46de5fa00f7ac09f020729148ff632819649b3e05a007d286242c4882f7b1dc3 --hash=sha256:a8dccd61d52a8dae4a825cdbb7735da530179fea472903eb871a5513b5abbfdc --hash=sha256:a5457d47dfff24882a21492e5815f891c0ca35fefae8aa742c6c263dac16ef1f --hash=sha256:ed851c75d1e0e043cbf5ca9a8e1b13c4c90f3fbd863dacb01c0808e2b5204201 --hash=sha256:a2e85dc204556657661051ff4bab75a84e968669765c8a2cd425918699c3d0e8 --hash=sha256:d2c5cfa536227f57f97c92ac30c8109688ace8fa4ac086d19d0af47d134e2909 --hash=sha256:5662ad4e4e84f1eaa8efce5da695c5d2e229c563f9d5ce5b0113f71321bcf753 --hash=sha256:4d0004eb4351e35ed950c14c11e734182591465a33e960a4ab5e8d4f04d72647 --hash=sha256:34c77afe85b6b9e967bd8154e3855e847b70ca42043db6ad17f26899a3df1b25 --hash=sha256:041c81822e9f84b1d9c401182e174996f0bae9991f33725d059b771744290774 --hash=sha256:4e3d3f31a1e202b0f5a35ba3bc4eb41e2fc2b11c1eff38b362de710bcffb5016 --hash=sha256:300832850b8f7967e278870c5d51e3819b9aad8f0a2c8dbe39ab11f119237f45 --hash=sha256:73e1ffefe05e4ccd7bcea61af76f36077b914f92b76f95ccf00b0c1b9186f3f9 --hash=sha256:066c7ff148ae33040c01058662d6752fd73fbc8e64787229ea8498c7d7f4041b --hash=sha256:d42b5796e20aacc9d15e66befb7a345454eef794fdb0737d1af593447c6c8f45 --hash=sha256:066bc4c7895c91812eff46f4b1c285220947d4aa46fa0a2651ff85f2afae9c90 --hash=sha256:046ef9a22f5d3eed06334d01b1e836977eeef500d9b78e9ef693f9380ad0b83d --hash=sha256:e1ff2748c84d97b065cc95429814cdba39bcbd77c9c85c89344b317dc0d9cbff --hash=sha256:b012a5edb48288f77a63dba0840c92d0504aa215612da4541b7b42d849bc83a3 --hash=sha256:59b4dc008f98fc6ee2bb4fd7fc786a8d70000d058c2bbe2698275bc53a8d3fa7 --hash=sha256:ae61af521ed676cf16ae94f30fe202781a38d7178b6b4ab622e4eec8cefaff42 --hash=sha256:55cad9a6df1e2a1d62063f79d0881a414a906a6962bc160ac968cc03ed3efcfb --hash=sha256:4aa8ee7ba27c472d429b980c51e714a24f47ca296d53f4d7868075b175866f4b --hash=sha256:a1f0fd46eba2d71ce1589f7e50a9e2ffaeb739fb2c11e8192aa2b45d5f6cc41f --hash=sha256:2444d0c61f03dcd26dbf7600cf64354376ee579acad77aef459e34efcb438c63 --hash=sha256:50bec6d35e6b1aaeb17f7c4e2b9374ebf95a8975d57863546fa83e8d31bdb8c4 --hash=sha256:e070535507bd6aa07124258171be2ee8dfc19119c28ca94c9dfb7efd23564512 --hash=sha256:dee54f5d30d775f525894d67b1495625dd9322945e7fee00731952e0368ff42d! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing chardet==3.0.4 --hash=sha256:fc323ffcaeaed0e0a02bf4d117757b98aed530d9ed4531e3e15460124c106691 --hash=sha256:84ab92ed1c4d4f16916e05906b6b75a6c0fb5db821cc65e70cbd64a3e2a5eaae! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django==2.2.1 --hash=sha256:6fcc3cbd55b16f9a01f37de8bcbe286e0ea22e87096557f1511051780338eaea --hash=sha256:bb407d0bb46395ca1241f829f5bd03f7e482f97f7d1936e26e98dacb201ed4ec! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing django-environ==0.4.5 --hash=sha256:6c9d87660142608f63ec7d5ce5564c49b603ea8ff25da595fd6098f6dc82afde --hash=sha256:c57b3c11ec1f319d9474e3e5a79134f40174b17c7cc024bbb2fad84646b120c4! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing gunicorn==19.9.0 --hash=sha256:fa2662097c66f920f53f70621c6c58ca4a3c4d3434205e608e121b5b3b71f4f3 --hash=sha256:aa8e0b40b4157b36a5df5e599f45c9c76d6af43845ba3b3b0efe2c70473c2471! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing idna==2.8 --hash=sha256:ea8b7f6188e6fa117537c3df7da9fc686d485087abf6ac197f9c46432f7e4a3c --hash=sha256:c357b3f628cf53ae2c4c05627ecc484553142ca23264e593d327bcde5e9c3407! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing multidict==4.5.2 --hash=sha256:1d1c77013a259971a72ddaa83b9f42c80a93ff12df6a4723be99d858fa30bee3 --hash=sha256:6a3a9b0f45fd75dc05d8e93dc21b18fc1670135ec9544d1ad4acbcf6b86781d0 --hash=sha256:7fc0eee3046041387cbace9314926aa48b681202f8897f8bff3809967a049036 --hash=sha256:068167c2d7bbeebd359665ac4fff756be5ffac9cda02375b5c5a7c4777038e73 --hash=sha256:4b843f8e1dd6a3195679d9838eb4670222e8b8d01bc36c9894d6c3538316fa0a --hash=sha256:7c1b7eab7a49aa96f3db1f716f0113a8a2e93c7375dd3d5d21c4941f1405c9c5 --hash=sha256:d1071414dd06ca2eafa90c85a079169bfeb0e5f57fd0b45d44c092546fcd6fd9 --hash=sha256:ce20044d0317649ddbb4e54dab3c1bcc7483c78c27d3f58ab3d0c7e6bc60d26a --hash=sha256:34f82db7f80c49f38b032c5abb605c458bac997a6c3142e0d6c130be6fb2b941 --hash=sha256:8ccd1c5fff1aa1427100ce188557fc31f1e0a383ad8ec42c559aabd4ff08802d --hash=sha256:8e08dd76de80539d613654915a2f5196dbccc67448df291e69a88712ea21e24a --hash=sha256:76ad8e4c69dadbb31bad17c16baee61c0d1a4a73bed2590b741b2e1a46d3edd0 --hash=sha256:61b2b33ede821b94fa99ce0b09c9ece049c7067a33b279f343adfe35108a4ea7 --hash=sha256:4a6ae52bd3ee41ee0f3acf4c60ceb3f44e0e3bc52ab7da1c2b2aa6703363a3d1 --hash=sha256:3d5dd8e5998fb4ace04789d1d008e2bb532de501218519d70bb672c4c5a2fc5d --hash=sha256:c49db89d602c24928e68c0d510f4fcf8989d77defd01c973d6cbe27e684833b1 --hash=sha256:041e9442b11409be5e4fc8b6a97e4bcead758ab1e11768d1e69160bdde18acc3 --hash=sha256:7ba19b777dc00194d1b473180d4ca89a054dd18de27d0ee2e42a103ec9b7d014 --hash=sha256:db603a1c235d110c860d5f39988ebc8218ee028f07a7cbc056ba6424372ca31b --hash=sha256:024b8129695a952ebd93373e45b5d341dbb87c17ce49637b34000093f243dd4f --hash=sha256:31dfa2fc323097f8ad7acd41aa38d7c614dd1960ac6681745b6da124093dc351 --hash=sha256:047c0a04e382ef8bd74b0de01407e8d8632d7d1b4db6f2561106af812a68741b --hash=sha256:d3be11ac43ab1a3e979dac80843b42226d5d3cccd3986f2e03152720a4297cd7 --hash=sha256:148ff60e0fffa2f5fad2eb25aae7bef23d8f3b8bdaf947a65cdbe84a978092bc --hash=sha256:1d48bc124a6b7a55006d97917f695effa9725d05abe8ee78fd60d6588b8344cd --hash=sha256:4b02a3b2a2f01d0490dd39321c74273fed0568568ea0e7ea23e02bd1fb10a10b --hash=sha256:5de53a28f40ef3c4fd57aeab6b590c2c663de87a5af76136ced519923d3efbb3 --hash=sha256:045b4dd0e5f6121e6f314d81759abd2c257db4634260abcfe0d3f7083c4908ef --hash=sha256:c18498c50c59263841862ea0501da9f2b3659c00db54abfbf823a80787fde8ce! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing praw==6.2.0 --hash=sha256:79767ebeae643ea3c99016d0611bd43976ed7dbde06d6c6f60564012f8523c5b --hash=sha256:290bafad69f3a478f5fb64a8f8d8bfe2dab215af7e5fad7737f910e38fc6b97f! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing prawcore==1.0.1 --hash=sha256:ab5558efb438aa73fc66c4178bfc809194dea3ce2addf4dec873de7e2fd2824e --hash=sha256:25dd14bf121bc0ad2ffc78e2322d9a01a516017105a5596cc21bb1e9a928b40c! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing psycopg2-binary==2.8.2 --hash=sha256:de24a4962e361c512d3e528ded6c7480eab24c655b8ca1f0b761d3b3650d2f07 --hash=sha256:fcbe7cf3a786572b73d2cd5f34ed452a5f5fac47c9c9d1e0642c457a148f9f88 --hash=sha256:d18c89957ac57dd2a2724ecfe9a759912d776f96ecabba23acb9ecbf5c731035 --hash=sha256:da0929b2bf0d1f365345e5eb940d8713c1d516312e010135b14402e2a3d2404d --hash=sha256:d7e7b0ff21f39433c50397e60bf0995d078802c591ca3b8d99857ea18a7496ee --hash=sha256:2eddc31500f73544a2a54123d4c4b249c3c711d31e64deddb0890982ea37397a --hash=sha256:4c2d9369ed40b4a44a8ccd6bc3a7db6272b8314812d2d1091f95c4c836d92e06 --hash=sha256:131c80d0958c89273d9720b9adf9df1d7600bb3120e16019a7389ab15b079af5 --hash=sha256:2de34cc3b775724623f86617d2601308083176a495f5b2efc2bbb0da154f483a --hash=sha256:484f6c62bdc166ee0e5be3aa831120423bf399786d1f3b0304526c86180fbc0b --hash=sha256:f046aeae1f7a845041b8661bb7a52449202b6c5d3fb59eb4724e7ca088811904 --hash=sha256:c1c9a33e46d7c12b9c96cf2d4349d783e3127163fd96254dcd44663cf0a1d438 --hash=sha256:b2cf82f55a619879f8557fdaae5cec7a294fac815e0087c4f67026fdf5259844 --hash=sha256:804914a669186e2843c1f7fbe12b55aad1b36d40a28274abe6027deffad9433d --hash=sha256:007ca0df127b1862fc010125bc4100b7a630efc6841047bd11afceadb4754611 --hash=sha256:a582416ad123291a82c300d1d872bdc4136d69ad0b41d57dc5ca3df7ef8e3088 --hash=sha256:70f570b5fa44413b9f30dbc053d17ef3ce6a4100147a10822f8662e58d473656 --hash=sha256:e45f93ff3f7dae2202248cf413a87aeb330821bf76998b3cf374eda2fc893dd7 --hash=sha256:0a1232cdd314e08848825edda06600455ad2a7adaa463ebfb12ece2d09f3370e --hash=sha256:7a2b5b095f3bd733aab101c89c0e1a3f0dfb4ebdc26f6374805c086ffe29d5b2 --hash=sha256:90da901fc33ea393fc644607e4a3916b509387e9339ec6ebc7bfded45b7a0ae9 --hash=sha256:03c49e02adf0b4d68f422fdbd98f7a7c547beb27e99a75ed02298f85cb48406a --hash=sha256:8520c03172da18345d012949a53617a963e0191ccb3c666f23276d5326af27b5 --hash=sha256:f1dc2b7b2748084b890f5d05b65a47cd03188824890e9a60818721fd492249fb --hash=sha256:b59d6f8cfca2983d8fdbe457bf95d2192f7b7efdb2b483bf5fa4e8981b04e8b2 --hash=sha256:be0f952f1c365061041bad16e27e224e29615d4eb1fb5b7e7760a1d3d12b90b6 --hash=sha256:ac8c5e20309f4989c296d62cac20ee456b69c41fd1bc03829e27de23b6fa9dd0 --hash=sha256:be08168197021d669b9964bd87628fa88f910b1be31e7010901070f2540c05fd! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing pycares==3.0.0 --hash=sha256:df9bc694cf03673878ea8ce674082c5acd134991d64d6c306d4bd61c0c1df98f --hash=sha256:2ca080db265ea238dc45f997f94effb62b979a617569889e265c26a839ed6305 --hash=sha256:755187d28d24a9ea63aa2b4c0638be31d65fbf7f0ce16d41261b9f8cb55a1b99 --hash=sha256:a11b7d63c3718775f6e805d6464cb10943780395ab042c7e5a0a7a9f612735dd --hash=sha256:cdb342e6a254f035bd976d95807a2184038fc088d957a5104dcaab8be602c093 --hash=sha256:90b27d4df86395f465a171386bc341098d6d47b65944df46518814ae298f6cc6 --hash=sha256:70918d06eb0603016d37092a5f2c0228509eb4e6c5a3faacb4184f6ab7be7650 --hash=sha256:c7f4f65e44ba35e35ad3febc844270665bba21cfb0fb7d749434e705b556e087 --hash=sha256:cf08e164f8bfb83b9fe633feb56f2754fae6baefcea663593794fa0518f8f98c --hash=sha256:7baa4b1f2146eb8423ff8303ebde3a20fb444a60db761fba0430d104fe35ddbf --hash=sha256:6f79c6afb6ce603009db2042fddc2e348ad093ece9784cbe2daa809499871a23 --hash=sha256:b253f5dcaa0ac7076b79388a3ac80dd8f3bd979108f813baade40d3a9b8bf0bd --hash=sha256:9e090dd6b2afa65cb51c133883b2bf2240fd0f717b130b0048714b33fb0f47ce! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing pycparser==2.19 --hash=sha256:a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing python-dateutil==2.8.0 --hash=sha256:c89805f6f4d64db21ed966fda138f8a5ed7a4fdbc1a8ee329ce1b74e3c74da9e --hash=sha256:7e6584c74aeed623791615e26efd690f29817a27c73085b78e4bad02493df2fb! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing pytz==2019.1 --hash=sha256:d747dd3d23d77ef44c6a3526e274af6efeb0a6f1afd5a69ba4d5be4098c8e141 --hash=sha256:303879e36b721603cc54604edcac9d20401bdbe31e1e4fdee5b9f98d5d31dfda! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing requests==2.22.0 --hash=sha256:11e007a8a2aa0323f5a921e9e6a2d7e4e67d9877e85773fba9ba6419025cbeb4 --hash=sha256:9cf5292fcd0f598c671cfc1e0d7d1a7f13bb8085e9a590f48c010551dc6c4b31! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing sentry-sdk==0.8.0 --hash=sha256:f5819df450d7b0696be69a0c6d70a09e4890a3844ee8ccb7a461794135bd5965 --hash=sha256:e308129104567cee9f8848ed5098de17cbccc19bd21417c8980d47f80f1409ec! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing six==1.12.0 --hash=sha256:3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c --hash=sha256:d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing slackclient==2.0.1 --hash=sha256:dccece1609fae52d23af5e9b7418c7b74a3a1040048cf8ffe416521a6f29b8a4 --hash=sha256:82cef9b4aa4180be440598807903f618f07aebc0f61afe3135b81870edb1b1ad! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing sqlparse==0.3.0 --hash=sha256:40afe6b8d4b1117e7dff5504d7a8ce07d9a1b15aeeade8a2d10f130a834f8177 --hash=sha256:7c3dca29c022744e95b547e867cee89f4fce4373f3549ccd8797d8eb52cdb873! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing update-checker==0.16 --hash=sha256:59cfad7f9a0ee99f95f1dfc60f55bf184937bcab46a7270341c2c33695572453 --hash=sha256:70e39446fccf77b21192cf7a8214051fa93a636dc3b5c8b602b589d100a168b8! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing urllib3==1.25.2 --hash=sha256:d363e3607d8de0c220d31950a8f38b18d5ba7c0830facd71a1c6b1036b7ce06c --hash=sha256:a53063d8b9210a7bdec15e7b272776b9d42b2fd6816401a0d43006ad2f9902db! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing websocket-client==0.56.0 --hash=sha256:1151d5fb3a62dc129164292e1227655e4bbc5dd5340a5165dfae61128ec50aa9 --hash=sha256:1fd5520878b68b84b5748bb30e592b10d0a91529d5383f74f4964e72b297fd3a! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing whitenoise==4.1.2 --hash=sha256:42133ddd5229eeb6a0c9899496bdbe56c292394bf8666da77deeb27454c0456a --hash=sha256:118ab3e5f815d380171b100b05b76de2a07612f422368a201a9ffdeefb2251c1! Will try again.\n\u001b[0m\u001b[91mAn error occurred while installing yarl==1.3.0 --hash=sha256:5badb97dd0abf26623a9982cd448ff12cb39b8e4c94032ccdedf22ce01a64842 --hash=sha256:b25de84a8c20540531526dfbb0e2d2b648c13fd5dd126728c496d7c3fea33310 --hash=sha256:e060906c0c585565c718d1c3841747b61c5439af2211e185f6739a9412dfbde1 --hash=sha256:73f447d11b530d860ca1e6b582f947688286ad16ca42256413083d13f260b7a0 --hash=sha256:3890ab952d508523ef4881457c4099056546593fa05e93da84c7250516e632eb --hash=sha256:c9bb7c249c4432cd47e75af3864bc02d26c9594f49c82e2a28624417f0ae63b8 --hash=sha256:3e2724eb9af5dc41648e5bb304fcf4891adc33258c6e14e2a7414ea32541e320 --hash=sha256:7ab825726f2940c16d92aaec7d204cfc34ac26c0040da727cf8ba87255a33829 --hash=sha256:c6e341f5a6562af74ba55205dbd56d248daf1b5748ec48a0200ba227bb9e33f4 --hash=sha256:2f3010703295fbe1aec51023740871e64bb9664c789cba5a6bdf404e93f7568f --hash=sha256:024ecdc12bc02b321bc66b41327f930d1c2c543fa9a561b39861da9388ba7aa9! Will try again.\n\u001b[0mInstalling initially failed dependencies...\n\u001b[91m[pipenv.exceptions.InstallError]: Collecting aiodns==2.0.0\n[pipenv.exceptions.InstallError]:   Using cached aiodns-2.0.0-py2.py3-none-any.whl (4.8 kB)\n[pipenv.exceptions.InstallError]: Collecting aiohttp==3.5.4\n[pipenv.exceptions.InstallError]:   Using cached aiohttp-3.5.4.tar.gz (1.1 MB)\n[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'\n[pipenv.exceptions.InstallError]: Collecting async-timeout==3.0.1\n[pipenv.exceptions.InstallError]:   Using cached async_timeout-3.0.1-py3-none-any.whl (8.2 kB)\n[pipenv.exceptions.InstallError]: Collecting attrs==19.1.0\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached attrs-19.1.0-py2.py3-none-any.whl (35 kB)\n[pipenv.exceptions.InstallError]: Collecting certifi==2019.3.9\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached certifi-2019.3.9-py2.py3-none-any.whl (158 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting cffi==1.12.3\n[pipenv.exceptions.InstallError]:   Using cached cffi-1.12.3.tar.gz (456 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting django==2.2.1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached Django-2.2.1-py3-none-any.whl (7.4 MB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting gunicorn==19.9.0\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached gunicorn-19.9.0-py2.py3-none-any.whl (112 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting idna==2.8\n[pipenv.exceptions.InstallError]:   Using cached idna-2.8-py2.py3-none-any.whl (58 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting multidict==4.5.2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached multidict-4.5.2.tar.gz (105 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started\n[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting psycopg2-binary==2.8.2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached psycopg2-binary-2.8.2.tar.gz (369 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting pycparser==2.19\n[pipenv.exceptions.InstallError]:   Using cached pycparser-2.19.tar.gz (158 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'\n[pipenv.exceptions.InstallError]: Collecting python-dateutil==2.8.0\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached python_dateutil-2.8.0-py2.py3-none-any.whl (226 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting requests==2.22.0\n[pipenv.exceptions.InstallError]:   Using cached requests-2.22.0-py2.py3-none-any.whl (57 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting six==1.12.0\n[pipenv.exceptions.InstallError]:   Using cached six-1.12.0-py2.py3-none-any.whl (10 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting slackclient==2.0.1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached slackclient-2.0.1-py2.py3-none-any.whl (24 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting sqlparse==0.3.0\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached sqlparse-0.3.0-py2.py3-none-any.whl (39 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting urllib3==1.25.2\n[pipenv.exceptions.InstallError]:   Using cached urllib3-1.25.2-py2.py3-none-any.whl (150 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting websocket-client==0.56.0\n[pipenv.exceptions.InstallError]:   Using cached websocket_client-0.56.0-py2.py3-none-any.whl (200 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Collecting yarl==1.3.0\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Using cached yarl-1.3.0.tar.gz (159 kB)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Preparing metadata (setup.py): finished with status 'done'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Building wheels for collected packages: aiohttp, cffi, multidict, psycopg2-binary, pycparser, yarl\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Building wheel for aiohttp (setup.py): started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Building wheel for aiohttp (setup.py): finished with status 'done'\n[pipenv.exceptions.InstallError]:   Created wheel for aiohttp: filename=aiohttp-3.5.4-py3-none-any.whl size=433140 sha256=906438c1d4379a840345251c76bddba25184c538867d170f0ed4b0bdc8caa3ac\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Stored in directory: /root/.cache/pipenv/wheels/c9/76/b3/e5304baade02b2c7f1e6c407e0e8627c2b20f75e824cbe3afc\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Building wheel for cffi (setup.py): started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Building wheel for cffi (setup.py): finished with status 'error'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Running setup.py clean for cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Building wheel for multidict (setup.py): started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Building wheel for multidict (setup.py): finished with status 'done'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Created wheel for multidict: filename=multidict-4.5.2-py3-none-any.whl size=90356 sha256=5026270b258cee81b5ee054f02b10719f0d910f2c2fc55073288c34d4dee72cc\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Stored in directory: /root/.cache/pipenv/wheels/21/89/8f/f8a68f37a7d1e08f21e0c131b59e457dc995165cecae1d3bb3\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Building wheel for psycopg2-binary (setup.py): started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Building wheel for psycopg2-binary (setup.py): finished with status 'error'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Running setup.py clean for psycopg2-binary\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Building wheel for pycparser (setup.py): started\n[pipenv.exceptions.InstallError]:   Building wheel for pycparser (setup.py): finished with status 'done'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Created wheel for pycparser: filename=pycparser-2.19-py2.py3-none-any.whl size=111052 sha256=e37672b3bc84a38e34c7b808ab9be0857cd9831498f644055bd9a245edfe885b\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Stored in directory: /root/.cache/pipenv/wheels/5e/c8/b1/b22ecffedea3c686a222847db199dda54bdfc842261423e157\n[pipenv.exceptions.InstallError]:   Building wheel for yarl (setup.py): started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Building wheel for yarl (setup.py): finished with status 'done'\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Created wheel for yarl: filename=yarl-1.3.0-py3-none-any.whl size=84912 sha256=3139f67f695061c6cd394595b6ffdbad8737831a47751b0d4982014e055d604a\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Stored in directory: /root/.cache/pipenv/wheels/6c/b6/87/fa402d246401b0bfe10454ee0c0d2c3e5513e04ff2c433c62a\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Successfully built aiohttp multidict pycparser yarl\n[pipenv.exceptions.InstallError]: Failed to build cffi psycopg2-binary\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: Installing collected packages: cffi, certifi, aiodns, yarl, websocket-client, urllib3, sqlparse, slackclient, six, requests, python-dateutil, pycparser, psycopg2-binary, multidict, idna, gunicorn, django, attrs, async-timeout, aiohttp\n[pipenv.exceptions.InstallError]:   Running setup.py install for cffi: started\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   Running setup.py install for cffi: finished with status 'error'\n[pipenv.exceptions.InstallError]: error: subprocess-exited-with-error\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   × python setup.py bdist_wheel did not run successfully.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   │ exit code: 1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   ╰─> [60 lines of output]\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       /usr/local/lib/python3.11/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         warnings.warn(msg, warning_class)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running bdist_wheel\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build_py\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-cpython-311\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/ffiplatform.py -> build/lib.linux-x86_64-cpython-311/cffi\n[pipenv.exceptions.InstallError]:       copying cffi/verifier.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/api.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/__init__.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/recompiler.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/pkgconfig.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/error.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/commontypes.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/vengine_gen.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/lock.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/model.py -> build/lib.linux-x86_64-cpython-311/cffi\n[pipenv.exceptions.InstallError]:       copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/cparser.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/_cffi_include.h -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/parse_c_type.h -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/_embedding.h -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: build_py: byte-compiling is disabled, skipping.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build_ext\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       building '_cffi_backend' extension\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/temp.linux-x86_64-cpython-311\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/temp.linux-x86_64-cpython-311/c\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/local/include/python3.11 -c c/_cffi_backend.c -o build/temp.linux-x86_64-cpython-311/c/_cffi_backend.o\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       c/_cffi_backend.c: In function ‘ctypedescr_dealloc’:\n[pipenv.exceptions.InstallError]:       c/_cffi_backend.c:405:23: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         405 |         Py_REFCNT(ct) = 43;\n[pipenv.exceptions.InstallError]:             |                       ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       c/_cffi_backend.c:408:23: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         408 |         Py_REFCNT(ct) = 0;\n[pipenv.exceptions.InstallError]:             |                       ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       c/_cffi_backend.c: In function ‘prepare_callback_info_tuple’:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       c/_cffi_backend.c:6029:5: warning: ‘PyEval_InitThreads’ is deprecated [-Wdeprecated-declarations]\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:        6029 |     PyEval_InitThreads();\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |     ^~~~~~~~~~~~~~~~~~\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       In file included from /usr/local/include/python3.11/Python.h:95,\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:                        from c/_cffi_backend.c:2:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       /usr/local/include/python3.11/ceval.h:132:37: note: declared here\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         132 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |                                     ^~~~~~~~~~~~~~~~~~\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       c/_cffi_backend.c: In function ‘b_callback’:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       c/_cffi_backend.c:6089:5: warning: ‘ffi_prep_closure’ is deprecated: use ffi_prep_closure_loc instead [-Wdeprecated-declarations]\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:        6089 |     if (ffi_prep_closure(closure, &cif_descr->cif,\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |     ^~\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       In file included from c/_cffi_backend.c:15:\n[pipenv.exceptions.InstallError]:       /usr/include/x86_64-linux-gnu/ffi.h:334:1: note: declared here\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         334 | ffi_prep_closure (ffi_closure*,\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             | ^~~~~~~~~~~~~~~~\n[pipenv.exceptions.InstallError]:       error: command '/usr/bin/gcc' failed with exit code 1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       [end of output]\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   ERROR: Failed building wheel for cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   error: subprocess-exited-with-error\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   × python setup.py bdist_wheel did not run successfully.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   │ exit code: 1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   ╰─> [73 lines of output]\n[pipenv.exceptions.InstallError]:       /usr/local/lib/python3.11/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         warnings.warn(msg, warning_class)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running bdist_wheel\n[pipenv.exceptions.InstallError]:       running build\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build_py\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-cpython-311\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/__init__.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n[pipenv.exceptions.InstallError]:       copying lib/pool.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/_ipaddress.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/errors.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/_json.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/sql.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/_lru_cache.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/compat.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n[pipenv.exceptions.InstallError]:       copying lib/_range.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/tz.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/extras.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/extensions.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying lib/errorcodes.py -> build/lib.linux-x86_64-cpython-311/psycopg2\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: build_py: byte-compiling is disabled, skipping.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build_ext\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       building 'psycopg2._psycopg' extension\n[pipenv.exceptions.InstallError]:       creating build/temp.linux-x86_64-cpython-311\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/temp.linux-x86_64-cpython-311/psycopg\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_asis.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_asis.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_binary.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_binary.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_datetime.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_datetime.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_list.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_list.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_pboolean.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_pboolean.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_pdecimal.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_pdecimal.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_pfloat.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_pfloat.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_pint.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_pint.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/adapter_qstring.c -o build/temp.linux-x86_64-cpython-311/psycopg/adapter_qstring.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/bytes_format.c -o build/temp.linux-x86_64-cpython-311/psycopg/bytes_format.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/column_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/column_type.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/connection_int.c -o build/temp.linux-x86_64-cpython-311/psycopg/connection_int.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/connection_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/connection_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/conninfo_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/conninfo_type.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/cursor_int.c -o build/temp.linux-x86_64-cpython-311/psycopg/cursor_int.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/cursor_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/cursor_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/diagnostics_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/diagnostics_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/error_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/error_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/green.c -o build/temp.linux-x86_64-cpython-311/psycopg/green.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/libpq_support.c -o build/temp.linux-x86_64-cpython-311/psycopg/libpq_support.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/lobject_int.c -o build/temp.linux-x86_64-cpython-311/psycopg/lobject_int.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/lobject_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/lobject_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/microprotocols.c -o build/temp.linux-x86_64-cpython-311/psycopg/microprotocols.o -Wdeclaration-after-statement\n[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/microprotocols_proto.c -o build/temp.linux-x86_64-cpython-311/psycopg/microprotocols_proto.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/notify_type.c -o build/temp.linux-x86_64-cpython-311/psycopg/notify_type.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/pqpath.c -o build/temp.linux-x86_64-cpython-311/psycopg/pqpath.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC \"-DPSYCOPG_VERSION=2.8.2 (dt dec pq3 ext lo64)\" -DPG_VERSION_NUM=130009 -DHAVE_LO64=1 -I/usr/local/include/python3.11 -I. -I/usr/include/postgresql -I/usr/include/postgresql/13/server -c psycopg/psycopgmodule.c -o build/temp.linux-x86_64-cpython-311/psycopg/psycopgmodule.o -Wdeclaration-after-statement\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c: In function ‘add_module_types’:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c:920:36: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         920 |         Py_TYPE(typetable[i].type) = &PyType_Type;\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |                                    ^\n[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c: In function ‘datetime_init’:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c:952:30: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         952 |     Py_TYPE(&pydatetimeType) = &PyType_Type;\n[pipenv.exceptions.InstallError]:             |                              ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c: In function ‘PyInit__psycopg’:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c:1084:28: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:        1084 |     Py_TYPE(&typecastType) = &PyType_Type;\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |                            ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c:1087:25: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:        1087 |     Py_TYPE(&chunkType) = &PyType_Type;\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |                         ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       psycopg/psycopgmodule.c:1090:25: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:        1090 |     Py_TYPE(&errorType) = &PyType_Type;\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |                         ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       error: command '/usr/bin/gcc' failed with exit code 1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       [end of output]\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.\n[pipenv.exceptions.InstallError]:   ERROR: Failed building wheel for psycopg2-binary\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   error: subprocess-exited-with-error\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   × Running setup.py install for cffi did not run successfully.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   │ exit code: 1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   ╰─> [62 lines of output]\n[pipenv.exceptions.InstallError]:       /usr/local/lib/python3.11/site-packages/setuptools/config/setupcfg.py:508: SetuptoolsDeprecationWarning: The license_file parameter is deprecated, use license_files instead.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         warnings.warn(msg, warning_class)\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running install\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       /usr/local/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.\n[pipenv.exceptions.InstallError]:         warnings.warn(\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build_py\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build\n[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-cpython-311\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/ffiplatform.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/verifier.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/api.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/__init__.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/recompiler.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/pkgconfig.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/setuptools_ext.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/error.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/commontypes.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/backend_ctypes.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/vengine_gen.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/lock.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/vengine_cpy.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/model.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/cffi_opcode.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/cparser.py -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/_cffi_include.h -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/parse_c_type.h -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/_embedding.h -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       copying cffi/_cffi_errors.h -> build/lib.linux-x86_64-cpython-311/cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       warning: build_py: byte-compiling is disabled, skipping.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       running build_ext\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       building '_cffi_backend' extension\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/temp.linux-x86_64-cpython-311\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       creating build/temp.linux-x86_64-cpython-311/c\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/local/include/python3.11 -c c/_cffi_backend.c -o build/temp.linux-x86_64-cpython-311/c/_cffi_backend.o\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       c/_cffi_backend.c: In function ‘ctypedescr_dealloc’:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       c/_cffi_backend.c:405:23: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         405 |         Py_REFCNT(ct) = 43;\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |                       ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       c/_cffi_backend.c:408:23: error: lvalue required as left operand of assignment\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         408 |         Py_REFCNT(ct) = 0;\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |                       ^\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       c/_cffi_backend.c: In function ‘prepare_callback_info_tuple’:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       c/_cffi_backend.c:6029:5: warning: ‘PyEval_InitThreads’ is deprecated [-Wdeprecated-declarations]\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:        6029 |     PyEval_InitThreads();\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |     ^~~~~~~~~~~~~~~~~~\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       In file included from /usr/local/include/python3.11/Python.h:95,\n[pipenv.exceptions.InstallError]:                        from c/_cffi_backend.c:2:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       /usr/local/include/python3.11/ceval.h:132:37: note: declared here\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         132 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |                                     ^~~~~~~~~~~~~~~~~~\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       c/_cffi_backend.c: In function ‘b_callback’:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       c/_cffi_backend.c:6089:5: warning: ‘ffi_prep_closure’ is deprecated: use ffi_prep_closure_loc instead [-Wdeprecated-declarations]\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:        6089 |     if (ffi_prep_closure(closure, &cif_descr->cif,\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:             |     ^~\n[pipenv.exceptions.InstallError]:       In file included from c/_cffi_backend.c:15:\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       /usr/include/x86_64-linux-gnu/ffi.h:334:1: note: declared here\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:         334 | ffi_prep_closure (ffi_closure*,\n[pipenv.exceptions.InstallError]:             | ^~~~~~~~~~~~~~~~\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       error: command '/usr/bin/gcc' failed with exit code 1\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:       [end of output]\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]:   note: This error originates from a subprocess, and is likely not a problem with pip.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: error: legacy-install-failure\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: × Encountered error while trying to install package.\n[pipenv.exceptions.InstallError]: ╰─> cffi\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: \n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: note: This is an issue with the package mentioned above, not pip.\n\u001b[0m\u001b[91m[pipenv.exceptions.InstallError]: hint: See above for output from the failure.\nERROR: Couldn't install package: [Requirement(_name='aiodns', vcs=None, req=NamedRequirement(name='aiodns', version='==2.0.0', req=Requirement.parse('aiodns==2.0.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=aiodns, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.0.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=aiodns==2.0.0)>), markers=None, _specifiers='==2.0.0', index=None, editable=False, hashes=frozenset({'sha256:815fdef4607474295d68da46978a54481dd1e7be153c7d60f9e72773cd38d77d', 'sha256:aaa5ac584f40fe778013df0aa6544bf157799bd3f608364b451840ed2c8688de'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=aiodns, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.0.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=aiodns==2.0.0)>, _ireq=None), Requirement(_name='aiohttp', vcs=None, req=NamedRequirement(name='aiohttp', version='==3.5.4', req=Requirement.parse('aiohttp==3.5.4'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=aiohttp, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===3.5.4, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=aiohttp==3.5.4)>), markers=None, _specifiers='==3.5.4', index=None, editable=False, hashes=frozenset({'sha256:6d5ec9b8948c3d957e75ea14d41e9330e1ac3fed24ec53766c780f82805140dc', 'sha256:a25237abf327530d9561ef751eef9511ab56fd9431023ca6f4803f1994104d72', 'sha256:0155af66de8c21b8dba4992aaeeabf55503caefae00067a3b1139f86d0ec50ed', 'sha256:87331d1d6810214085a50749160196391a712a13336cd02ce1c3ea3d05bcf8d5', 'sha256:09654a9eca62d1bd6d64aa44db2498f60a5c1e0ac4750953fdd79d5c88955e10', 'sha256:199f1d106e2b44b6dacdf6f9245493c7d716b01d0b7fbe1959318ba4dc64d1f5', 'sha256:b05bd85cc99b06740aad3629c2585bda7b83bd86e080b44ba47faf905fdf1300', 'sha256:9cddaff94c0135ee627213ac6ca6d05724bfe6e7a356e5e09ec57bd3249510f6', 'sha256:a97a516e02b726e089cffcde2eea0d3258450389bbac48cbe89e0f0b6e7b0366', 'sha256:cc619d974c8c11fe84527e4b5e1c07238799a8c29ea1c1285149170524ba9303', 'sha256:629102a193162e37102c50713e2e31dc9a2fe7ac5e481da83e5bb3c0cee700aa', 'sha256:9a02a04bbe581c8605ac423ba3a74999ec9d8bce7ae37977a3d38680f5780b6d', 'sha256:00d198585474299c9c3b4f1d5de1a576cc230d562abc5e4a0e81d71a20a6ca55', 'sha256:296f30dedc9f4b9e7a301e5cc963012264112d78a1d3094cd83ef148fdf33ca1', 'sha256:c2bec436a2b5dafe5eaeb297c03711074d46b6eb236d002c13c42f25c4a8ce9d', 'sha256:d4392defd4648badaa42b3e101080ae3313e8f4787cb517efd3f5b8157eaefd6', 'sha256:acc89b29b5f4e2332d65cd1b7d10c609a75b88ef8925d487a611ca788432dfa4', 'sha256:a5cbd7157b0e383738b8e29d6e556fde8726823dae0e348952a61742b21aeb12', 'sha256:40d7ea570b88db017c51392349cf99b7aefaaddd19d2c78368aeb0bddde9d390', 'sha256:368ed312550bd663ce84dc4b032a962fcb3c7cae099dbbd48663afc305e3b939', 'sha256:9c4c83f4fa1938377da32bc2d59379025ceeee8e24b89f72fcbccd8ca22dc9bf', 'sha256:e1c3c582ee11af7f63a34a46f0448fca58e59889396ffdae1f482085061a2889'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=aiohttp, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===3.5.4, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=aiohttp==3.5.4)>, _ireq=None), Requirement(_name='async-timeout', vcs=None, req=NamedRequirement(name='async-timeout', version='==3.0.1', req=Requirement.parse('async-timeout==3.0.1'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=async-timeout, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===3.0.1, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=async-timeout==3.0.1)>), markers=None, _specifiers='==3.0.1', index=None, editable=False, hashes=frozenset({'sha256:4291ca197d287d274d0b6cb5d6f8f8f82d434ed288f962539ff18cc9012f9ea3', 'sha256:0c3c816a028d47f659d6ff5c745cb2acf1f966da1fe5c19c77a70282b25f4c5f'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=async-timeout, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===3.0.1, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=async-timeout==3.0.1)>, _ireq=None), Requirement(_name='attrs', vcs=None, req=NamedRequirement(name='attrs', version='==19.1.0', req=Requirement.parse('attrs==19.1.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=attrs, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===19.1.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=attrs==19.1.0)>), markers=None, _specifiers='==19.1.0', index=None, editable=False, hashes=frozenset({'sha256:69c0dbf2ed392de1cb5ec704444b08a5ef81680a61cb899dc08127123af36a79', 'sha256:f0b870f674851ecbfbbbd364d6b5cbdff9dcedbc7f3f5e18a6891057f21fe399'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=attrs, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===19.1.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=attrs==19.1.0)>, _ireq=None), Requirement(_name='certifi', vcs=None, req=NamedRequirement(name='certifi', version='==2019.3.9', req=Requirement.parse('certifi==2019.3.9'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=certifi, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2019.3.9, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=certifi==2019.3.9)>), markers=None, _specifiers='==2019.3.9', index=None, editable=False, hashes=frozenset({'sha256:59b7658e26ca9c7339e00f8f4636cdfe59d34fa37b9b04f6f9e9926b3cece1a5', 'sha256:b26104d6835d1f5e49452a26eb2ff87fe7090b89dfcaee5ea2212697e1e1d7ae'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=certifi, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2019.3.9, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=certifi==2019.3.9)>, _ireq=None), Requirement(_name='cffi', vcs=None, req=NamedRequirement(name='cffi', version='==1.12.3', req=Requirement.parse('cffi==1.12.3'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=cffi, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===1.12.3, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=cffi==1.12.3)>), markers=None, _specifiers='==1.12.3', index=None, editable=False, hashes=frozenset({'sha256:46de5fa00f7ac09f020729148ff632819649b3e05a007d286242c4882f7b1dc3', 'sha256:a8dccd61d52a8dae4a825cdbb7735da530179fea472903eb871a5513b5abbfdc', 'sha256:a5457d47dfff24882a21492e5815f891c0ca35fefae8aa742c6c263dac16ef1f', 'sha256:ed851c75d1e0e043cbf5ca9a8e1b13c4c90f3fbd863dacb01c0808e2b5204201', 'sha256:a2e85dc204556657661051ff4bab75a84e968669765c8a2cd425918699c3d0e8', 'sha256:d2c5cfa536227f57f97c92ac30c8109688ace8fa4ac086d19d0af47d134e2909', 'sha256:5662ad4e4e84f1eaa8efce5da695c5d2e229c563f9d5ce5b0113f71321bcf753', 'sha256:4d0004eb4351e35ed950c14c11e734182591465a33e960a4ab5e8d4f04d72647', 'sha256:34c77afe85b6b9e967bd8154e3855e847b70ca42043db6ad17f26899a3df1b25', 'sha256:041c81822e9f84b1d9c401182e174996f0bae9991f33725d059b771744290774', 'sha256:4e3d3f31a1e202b0f5a35ba3bc4eb41e2fc2b11c1eff38b362de710bcffb5016', 'sha256:300832850b8f7967e278870c5d51e3819b9aad8f0a2c8dbe39ab11f119237f45', 'sha256:73e1ffefe05e4ccd7bcea61af76f36077b914f92b76f95ccf00b0c1b9186f3f9', 'sha256:066c7ff148ae33040c01058662d6752fd73fbc8e64787229ea8498c7d7f4041b', 'sha256:d42b5796e20aacc9d15e66befb7a345454eef794fdb0737d1af593447c6c8f45', 'sha256:066bc4c7895c91812eff46f4b1c285220947d4aa46fa0a2651ff85f2afae9c90', 'sha256:046ef9a22f5d3eed06334d01b1e836977eeef500d9b78e9ef693f9380ad0b83d', 'sha256:e1ff2748c84d97b065cc95429814cdba39bcbd77c9c85c89344b317dc0d9cbff', 'sha256:b012a5edb48288f77a63dba0840c92d0504aa215612da4541b7b42d849bc83a3', 'sha256:59b4dc008f98fc6ee2bb4fd7fc786a8d70000d058c2bbe2698275bc53a8d3fa7', 'sha256:ae61af521ed676cf16ae94f30fe202781a38d7178b6b4ab622e4eec8cefaff42', 'sha256:55cad9a6df1e2a1d62063f79d0881a414a906a6962bc160ac968cc03ed3efcfb', 'sha256:4aa8ee7ba27c472d429b980c51e714a24f47ca296d53f4d7868075b175866f4b', 'sha256:a1f0fd46eba2d71ce1589f7e50a9e2ffaeb739fb2c11e8192aa2b45d5f6cc41f', 'sha256:2444d0c61f03dcd26dbf7600cf64354376ee579acad77aef459e34efcb438c63', 'sha256:50bec6d35e6b1aaeb17f7c4e2b9374ebf95a8975d57863546fa83e8d31bdb8c4', 'sha256:e070535507bd6aa07124258171be2ee8dfc19119c28ca94c9dfb7efd23564512', 'sha256:dee54f5d30d775f525894d67b1495625dd9322945e7fee00731952e0368ff42d'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=cffi, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===1.12.3, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=cffi==1.12.3)>, _ireq=None), Requirement(_name='django', vcs=None, req=NamedRequirement(name='django', version='==2.2.1', req=Requirement.parse('django==2.2.1'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=django, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.2.1, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django==2.2.1)>), markers=None, _specifiers='==2.2.1', index='pypi', editable=False, hashes=frozenset({'sha256:6fcc3cbd55b16f9a01f37de8bcbe286e0ea22e87096557f1511051780338eaea', 'sha256:bb407d0bb46395ca1241f829f5bd03f7e482f97f7d1936e26e98dacb201ed4ec'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=django, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.2.1, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=django==2.2.1)>, _ireq=None), Requirement(_name='gunicorn', vcs=None, req=NamedRequirement(name='gunicorn', version='==19.9.0', req=Requirement.parse('gunicorn==19.9.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=gunicorn, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===19.9.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=gunicorn==19.9.0)>), markers=None, _specifiers='==19.9.0', index='pypi', editable=False, hashes=frozenset({'sha256:fa2662097c66f920f53f70621c6c58ca4a3c4d3434205e608e121b5b3b71f4f3', 'sha256:aa8e0b40b4157b36a5df5e599f45c9c76d6af43845ba3b3b0efe2c70473c2471'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=gunicorn, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===19.9.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=gunicorn==19.9.0)>, _ireq=None), Requirement(_name='idna', vcs=None, req=NamedRequirement(name='idna', version='==2.8', req=Requirement.parse('idna==2.8'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=idna, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.8, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=idna==2.8)>), markers=None, _specifiers='==2.8', index=None, editable=False, hashes=frozenset({'sha256:ea8b7f6188e6fa117537c3df7da9fc686d485087abf6ac197f9c46432f7e4a3c', 'sha256:c357b3f628cf53ae2c4c05627ecc484553142ca23264e593d327bcde5e9c3407'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=idna, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.8, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=idna==2.8)>, _ireq=None), Requirement(_name='multidict', vcs=None, req=NamedRequirement(name='multidict', version='==4.5.2', req=Requirement.parse('multidict==4.5.2'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=multidict, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===4.5.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=multidict==4.5.2)>), markers=None, _specifiers='==4.5.2', index=None, editable=False, hashes=frozenset({'sha256:1d1c77013a259971a72ddaa83b9f42c80a93ff12df6a4723be99d858fa30bee3', 'sha256:6a3a9b0f45fd75dc05d8e93dc21b18fc1670135ec9544d1ad4acbcf6b86781d0', 'sha256:7fc0eee3046041387cbace9314926aa48b681202f8897f8bff3809967a049036', 'sha256:068167c2d7bbeebd359665ac4fff756be5ffac9cda02375b5c5a7c4777038e73', 'sha256:4b843f8e1dd6a3195679d9838eb4670222e8b8d01bc36c9894d6c3538316fa0a', 'sha256:7c1b7eab7a49aa96f3db1f716f0113a8a2e93c7375dd3d5d21c4941f1405c9c5', 'sha256:d1071414dd06ca2eafa90c85a079169bfeb0e5f57fd0b45d44c092546fcd6fd9', 'sha256:ce20044d0317649ddbb4e54dab3c1bcc7483c78c27d3f58ab3d0c7e6bc60d26a', 'sha256:34f82db7f80c49f38b032c5abb605c458bac997a6c3142e0d6c130be6fb2b941', 'sha256:8ccd1c5fff1aa1427100ce188557fc31f1e0a383ad8ec42c559aabd4ff08802d', 'sha256:8e08dd76de80539d613654915a2f5196dbccc67448df291e69a88712ea21e24a', 'sha256:76ad8e4c69dadbb31bad17c16baee61c0d1a4a73bed2590b741b2e1a46d3edd0', 'sha256:61b2b33ede821b94fa99ce0b09c9ece049c7067a33b279f343adfe35108a4ea7', 'sha256:4a6ae52bd3ee41ee0f3acf4c60ceb3f44e0e3bc52ab7da1c2b2aa6703363a3d1', 'sha256:3d5dd8e5998fb4ace04789d1d008e2bb532de501218519d70bb672c4c5a2fc5d', 'sha256:c49db89d602c24928e68c0d510f4fcf8989d77defd01c973d6cbe27e684833b1', 'sha256:041e9442b11409be5e4fc8b6a97e4bcead758ab1e11768d1e69160bdde18acc3', 'sha256:7ba19b777dc00194d1b473180d4ca89a054dd18de27d0ee2e42a103ec9b7d014', 'sha256:db603a1c235d110c860d5f39988ebc8218ee028f07a7cbc056ba6424372ca31b', 'sha256:024b8129695a952ebd93373e45b5d341dbb87c17ce49637b34000093f243dd4f', 'sha256:31dfa2fc323097f8ad7acd41aa38d7c614dd1960ac6681745b6da124093dc351', 'sha256:047c0a04e382ef8bd74b0de01407e8d8632d7d1b4db6f2561106af812a68741b', 'sha256:d3be11ac43ab1a3e979dac80843b42226d5d3cccd3986f2e03152720a4297cd7', 'sha256:148ff60e0fffa2f5fad2eb25aae7bef23d8f3b8bdaf947a65cdbe84a978092bc', 'sha256:1d48bc124a6b7a55006d97917f695effa9725d05abe8ee78fd60d6588b8344cd', 'sha256:4b02a3b2a2f01d0490dd39321c74273fed0568568ea0e7ea23e02bd1fb10a10b', 'sha256:5de53a28f40ef3c4fd57aeab6b590c2c663de87a5af76136ced519923d3efbb3', 'sha256:045b4dd0e5f6121e6f314d81759abd2c257db4634260abcfe0d3f7083c4908ef', 'sha256:c18498c50c59263841862ea0501da9f2b3659c00db54abfbf823a80787fde8ce'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=multidict, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===4.5.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=multidict==4.5.2)>, _ireq=None), Requirement(_name='psycopg2-binary', vcs=None, req=NamedRequirement(name='psycopg2-binary', version='==2.8.2', req=Requirement.parse('psycopg2-binary==2.8.2'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=psycopg2-binary, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.8.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=psycopg2-binary==2.8.2)>), markers=None, _specifiers='==2.8.2', index='pypi', editable=False, hashes=frozenset({'sha256:de24a4962e361c512d3e528ded6c7480eab24c655b8ca1f0b761d3b3650d2f07', 'sha256:fcbe7cf3a786572b73d2cd5f34ed452a5f5fac47c9c9d1e0642c457a148f9f88', 'sha256:d18c89957ac57dd2a2724ecfe9a759912d776f96ecabba23acb9ecbf5c731035', 'sha256:da0929b2bf0d1f365345e5eb940d8713c1d516312e010135b14402e2a3d2404d', 'sha256:d7e7b0ff21f39433c50397e60bf0995d078802c591ca3b8d99857ea18a7496ee', 'sha256:2eddc31500f73544a2a54123d4c4b249c3c711d31e64deddb0890982ea37397a', 'sha256:4c2d9369ed40b4a44a8ccd6bc3a7db6272b8314812d2d1091f95c4c836d92e06', 'sha256:131c80d0958c89273d9720b9adf9df1d7600bb3120e16019a7389ab15b079af5', 'sha256:2de34cc3b775724623f86617d2601308083176a495f5b2efc2bbb0da154f483a', 'sha256:484f6c62bdc166ee0e5be3aa831120423bf399786d1f3b0304526c86180fbc0b', 'sha256:f046aeae1f7a845041b8661bb7a52449202b6c5d3fb59eb4724e7ca088811904', 'sha256:c1c9a33e46d7c12b9c96cf2d4349d783e3127163fd96254dcd44663cf0a1d438', 'sha256:b2cf82f55a619879f8557fdaae5cec7a294fac815e0087c4f67026fdf5259844', 'sha256:804914a669186e2843c1f7fbe12b55aad1b36d40a28274abe6027deffad9433d', 'sha256:007ca0df127b1862fc010125bc4100b7a630efc6841047bd11afceadb4754611', 'sha256:a582416ad123291a82c300d1d872bdc4136d69ad0b41d57dc5ca3df7ef8e3088', 'sha256:70f570b5fa44413b9f30dbc053d17ef3ce6a4100147a10822f8662e58d473656', 'sha256:e45f93ff3f7dae2202248cf413a87aeb330821bf76998b3cf374eda2fc893dd7', 'sha256:0a1232cdd314e08848825edda06600455ad2a7adaa463ebfb12ece2d09f3370e', 'sha256:7a2b5b095f3bd733aab101c89c0e1a3f0dfb4ebdc26f6374805c086ffe29d5b2', 'sha256:90da901fc33ea393fc644607e4a3916b509387e9339ec6ebc7bfded45b7a0ae9', 'sha256:03c49e02adf0b4d68f422fdbd98f7a7c547beb27e99a75ed02298f85cb48406a', 'sha256:8520c03172da18345d012949a53617a963e0191ccb3c666f23276d5326af27b5', 'sha256:f1dc2b7b2748084b890f5d05b65a47cd03188824890e9a60818721fd492249fb', 'sha256:b59d6f8cfca2983d8fdbe457bf95d2192f7b7efdb2b483bf5fa4e8981b04e8b2', 'sha256:be0f952f1c365061041bad16e27e224e29615d4eb1fb5b7e7760a1d3d12b90b6', 'sha256:ac8c5e20309f4989c296d62cac20ee456b69c41fd1bc03829e27de23b6fa9dd0', 'sha256:be08168197021d669b9964bd87628fa88f910b1be31e7010901070f2540c05fd'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=psycopg2-binary, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.8.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=psycopg2-binary==2.8.2)>, _ireq=None), Requirement(_name='pycparser', vcs=None, req=NamedRequirement(name='pycparser', version='==2.19', req=Requirement.parse('pycparser==2.19'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=pycparser, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.19, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=pycparser==2.19)>), markers=None, _specifiers='==2.19', index=None, editable=False, hashes=frozenset({'sha256:a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=pycparser, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.19, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=pycparser==2.19)>, _ireq=None), Requirement(_name='python-dateutil', vcs=None, req=NamedRequirement(name='python-dateutil', version='==2.8.0', req=Requirement.parse('python-dateutil==2.8.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=python-dateutil, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.8.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=python-dateutil==2.8.0)>), markers=None, _specifiers='==2.8.0', index='pypi', editable=False, hashes=frozenset({'sha256:c89805f6f4d64db21ed966fda138f8a5ed7a4fdbc1a8ee329ce1b74e3c74da9e', 'sha256:7e6584c74aeed623791615e26efd690f29817a27c73085b78e4bad02493df2fb'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=python-dateutil, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.8.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=python-dateutil==2.8.0)>, _ireq=None), Requirement(_name='requests', vcs=None, req=NamedRequirement(name='requests', version='==2.22.0', req=Requirement.parse('requests==2.22.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=requests, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.22.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=requests==2.22.0)>), markers=None, _specifiers='==2.22.0', index='pypi', editable=False, hashes=frozenset({'sha256:11e007a8a2aa0323f5a921e9e6a2d7e4e67d9877e85773fba9ba6419025cbeb4', 'sha256:9cf5292fcd0f598c671cfc1e0d7d1a7f13bb8085e9a590f48c010551dc6c4b31'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=requests, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.22.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=requests==2.22.0)>, _ireq=None), Requirement(_name='six', vcs=None, req=NamedRequirement(name='six', version='==1.12.0', req=Requirement.parse('six==1.12.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=six, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===1.12.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=six==1.12.0)>), markers=None, _specifiers='==1.12.0', index=None, editable=False, hashes=frozenset({'sha256:3350809f0555b11f552448330d0b52d5f24c91a322ea4a15ef22629740f3761c', 'sha256:d16a0141ec1a18405cd4ce8b4613101da75da0e9a7aec5bdd4fa804d0e0eba73'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=six, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===1.12.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=six==1.12.0)>, _ireq=None), Requirement(_name='slackclient', vcs=None, req=NamedRequirement(name='slackclient', version='==2.0.1', req=Requirement.parse('slackclient==2.0.1'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=slackclient, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.0.1, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=slackclient==2.0.1)>), markers=None, _specifiers='==2.0.1', index='pypi', editable=False, hashes=frozenset({'sha256:dccece1609fae52d23af5e9b7418c7b74a3a1040048cf8ffe416521a6f29b8a4', 'sha256:82cef9b4aa4180be440598807903f618f07aebc0f61afe3135b81870edb1b1ad'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=slackclient, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===2.0.1, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=slackclient==2.0.1)>, _ireq=None), Requirement(_name='sqlparse', vcs=None, req=NamedRequirement(name='sqlparse', version='==0.3.0', req=Requirement.parse('sqlparse==0.3.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=sqlparse, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===0.3.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=sqlparse==0.3.0)>), markers=None, _specifiers='==0.3.0', index=None, editable=False, hashes=frozenset({'sha256:40afe6b8d4b1117e7dff5504d7a8ce07d9a1b15aeeade8a2d10f130a834f8177', 'sha256:7c3dca29c022744e95b547e867cee89f4fce4373f3549ccd8797d8eb52cdb873'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=sqlparse, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===0.3.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=sqlparse==0.3.0)>, _ireq=None), Requirement(_name='urllib3', vcs=None, req=NamedRequirement(name='urllib3', version='==1.25.2', req=Requirement.parse('urllib3==1.25.2'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=urllib3, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===1.25.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=urllib3==1.25.2)>), markers=None, _specifiers='==1.25.2', index=None, editable=False, hashes=frozenset({'sha256:d363e3607d8de0c220d31950a8f38b18d5ba7c0830facd71a1c6b1036b7ce06c', 'sha256:a53063d8b9210a7bdec15e7b272776b9d42b2fd6816401a0d43006ad2f9902db'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=urllib3, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===1.25.2, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=urllib3==1.25.2)>, _ireq=None), Requirement(_name='websocket-client', vcs=None, req=NamedRequirement(name='websocket-client', version='==0.56.0', req=Requirement.parse('websocket-client==0.56.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=websocket-client, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===0.56.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=websocket-client==0.56.0)>), markers=None, _specifiers='==0.56.0', index=None, editable=False, hashes=frozenset({'sha256:1151d5fb3a62dc129164292e1227655e4bbc5dd5340a5165dfae61128ec50aa9', 'sha256:1fd5520878b68b84b5748bb30e592b10d0a91529d5383f74f4964e72b297fd3a'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=websocket-client, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===0.56.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=websocket-client==0.56.0)>, _ireq=None), Requirement(_name='yarl', vcs=None, req=NamedRequirement(name='yarl', version='==1.3.0', req=Requirement.parse('yarl==1.3.0'), extras=[], editable=False, _parsed_line=<Line (editable=False, name=yarl, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===1.3.0, pyproject=None, pyproject_requires=None, pyproject\u001b[0m\u001b[91m_backend=None, ireq=yarl==1.3.0)>), markers=None, _specifiers='==1.3.0', index=None, editable=False, hashes=frozenset({'sha256:5badb97dd0abf26623a9982cd448ff12cb39b8e4c94032ccdedf22ce01a64842', 'sha256:b25de84a8c20540531526dfbb0e2d2b648c13fd5dd126728c496d7c3fea33310', 'sha256:e060906c0c585565c718d1c3841747b61c5439af2211e185f6739a9412dfbde1', 'sha256:73f447d11b530d860ca1e6b582f947688286ad16ca42256413083d13f260b7a0', 'sha256:3890ab952d508523ef4881457c4099056546593fa05e93da84c7250516e632eb', 'sha256:c9bb7c249c4432cd47e75af3864bc02d26c9594f49c82e2a28624417f0ae63b8', 'sha256:3e2724eb9af5dc41648e5bb304fcf4891adc33258c6e14e2a7414ea32541e320', 'sha256:7ab825726f2940c16d92aaec7d204cfc34ac26c0040da727cf8ba87255a33829', 'sha256:c6e341f5a6562af74ba55205dbd56d248daf1b5748ec48a0200ba227bb9e33f4', 'sha256:2f3010703295fbe1aec51023740871e64bb9664c789cba5a6bdf404e93f7568f', 'sha256:024ecdc12bc02b321bc66b41327f930d1c2c543fa9a561b39861da9388ba7aa9'}), extras=(), abstract_dep=None, _line_instance=<Line (editable=False, name=yarl, path=None, uri=None, extras=(), markers=None, vcs=None, specifier===1.3.0, pyproject=None, pyproject_requires=None, pyproject_backend=None, ireq=yarl==1.3.0)>, _ireq=None)]\n Package installation failed...\n\u001b[0mRemoving intermediate container 51522a2b3b3d\n","stderr":"The command '/bin/sh -c set -ex && pipenv install --deploy --system' returned a non-zero code: 1\n"},"endTime":1672817069979}