{"repository":"https://github.com/daskos/mentos","dockerfilePath":"Dockerfile","startTime":1672302665564,"clone":{"stdout":"","stderr":"Cloning into '/tmp/dinghy-analysis/daskos/mentos'...\n","error":null,"commit":"1cecdb85feb42facf701bb709020a312f85f044e"},"originalBuild":{"startTimestamp":1672302666433,"endTimestamp":1672302679868,"error":{"code":1,"killed":false,"signal":null,"cmd":"docker build --no-cache --force-rm -t mentos:latest -f /tmp/dinghy-analysis/daskos/mentos/Dockerfile ."},"stdout":"Sending build context to Docker daemon  144.4kB\r\r\nStep 1/4 : FROM python:3.5.2-alpine\n3.5.2-alpine: Pulling from library/python\nb7f33cc0b48e: Pulling fs layer\n8eda8bb6fee4: Pulling fs layer\n4613e2ad30ef: Pulling fs layer\nf344c00ca799: Pulling fs layer\nf344c00ca799: Waiting\nb7f33cc0b48e: Verifying Checksum\nb7f33cc0b48e: Download complete\n8eda8bb6fee4: Verifying Checksum\n8eda8bb6fee4: Download complete\nf344c00ca799: Download complete\nb7f33cc0b48e: Pull complete\n4613e2ad30ef: Verifying Checksum\n4613e2ad30ef: Download complete\n8eda8bb6fee4: Pull complete\n4613e2ad30ef: Pull complete\nf344c00ca799: Pull complete\nDigest: sha256:8efcb12747ff958de32b32424813708f949c472ae48ca28691078475b3373e7c\nStatus: Downloaded newer image for python:3.5.2-alpine\n ---> e70a322afafb\nStep 2/4 : ADD . /mentos\n ---> 947f542b6d91\nStep 3/4 : WORKDIR /mentos\n ---> Running in d674becae427\nRemoving intermediate container d674becae427\n ---> 3ab77de10c1c\nStep 4/4 : RUN pip install .\n ---> Running in 1e0320b85ea3\nProcessing /mentos\n    Complete output from command python setup.py egg_info:\n    Couldn't find index page for 'pypandoc' (maybe misspelled?)\n    No local packages or download links found for pypandoc\n    Traceback (most recent call last):\n      File \"<string>\", line 1, in <module>\n      File \"/tmp/pip-8q1p6pyb-build/setup.py\", line 36, in <module>\n        zip_safe=True)\n      File \"/usr/local/lib/python3.5/distutils/core.py\", line 108, in setup\n        _setup_distribution = dist = klass(attrs)\n      File \"/usr/local/lib/python3.5/site-packages/setuptools/dist.py\", line 269, in __init__\n        self.fetch_build_eggs(attrs['setup_requires'])\n      File \"/usr/local/lib/python3.5/site-packages/setuptools/dist.py\", line 313, in fetch_build_eggs\n        replace_conflicting=True,\n      File \"/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py\", line 826, in resolve\n        dist = best[req.key] = env.best_match(req, ws, installer)\n      File \"/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py\", line 1092, in best_match\n        return self.obtain(req, installer)\n      File \"/usr/local/lib/python3.5/site-packages/pkg_resources/__init__.py\", line 1104, in obtain\n        return installer(requirement)\n      File \"/usr/local/lib/python3.5/site-packages/setuptools/dist.py\", line 380, in fetch_build_egg\n        return cmd.easy_install(req)\n      File \"/usr/local/lib/python3.5/site-packages/setuptools/command/easy_install.py\", line 634, in easy_install\n        raise DistutilsError(msg)\n    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pypandoc')\n    Warning: pypandoc module not found, could not convert Markdown to RST\n    \n    ----------------------------------------\n\u001b[91mCommand \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-8q1p6pyb-build/\n\u001b[0m\u001b[91mYou are using pip version 9.0.1, however version 22.3.1 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n\u001b[0mRemoving intermediate container 1e0320b85ea3\n","stderr":"The command '/bin/sh -c pip install .' returned a non-zero code: 1\n"},"endTime":1672302679947}